import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Percent } from "lucide-react";
import SiteHeader from "@/components/site-header";

const pages={
 about:{title:"About Amarildo Tools",description:"Amarildo Tools provides clear, useful calculators and converters that work without sign-up.",sections:[["Useful answers without the clutter","Amarildo Tools is a library of 300 calculators, converters, and practical digital tools. We focus on direct answers, understandable methods, responsive design, and simple navigation."],["How we build tools","Each published tool must perform a real task, identify its formula or method, and explain how to use the result. We test calculations and review pages as the library grows."],["Important limitations","Calculators can support planning, but estimates do not replace financial, medical, legal, engineering, tax, or other professional advice."]] },
 privacy:{title:"Privacy Policy",description:"Learn how Amarildo Tools handles calculator entries and basic website information.",sections:[["Calculator data","Amarildo Tools calculators are designed to process entries inside your browser whenever possible. We do not require an account to use the public calculators."],["Analytics and advertising","The public website may use privacy-conscious analytics and, in the future, advertising technologies. This policy will be updated before those services are activated."],["Your choices","You can use browser settings to control cookies and clear locally stored website information. Do not enter confidential information into a general-purpose calculator."]] },
 terms:{title:"Terms of Use",description:"Review the terms that apply when using Amarildo Tools calculators and utilities.",sections:[["Informational use","Amarildo Tools provides general-purpose calculation and conversion tools. Results are provided for informational and planning purposes."],["No professional advice","Nothing on Amarildo Tools is financial, tax, medical, legal, engineering, or investment advice. Check important decisions with an appropriately qualified professional."],["Responsible use","You may use the tools for lawful purposes. Do not attempt to disrupt the website, misuse its services, or rely on an estimate where certified calculations are required."]] },
 disclaimer:{title:"Calculator Disclaimer",description:"Understand the limits of estimates and results produced by Amarildo Tools.",sections:[["Results are estimates","We work to make formulas accurate, but input errors, rounding, changing rules, local requirements, and real-world conditions can change outcomes."],["Verify important decisions","Confirm important financial, construction, health, tax, and business calculations using authoritative documents or a qualified professional."],["No guarantees","Amarildo Tools does not guarantee that every result is complete or suitable for a particular decision."]] },
 contact:{title:"Contact Amarildo Tools",description:"Send feedback, corrections, or tool suggestions to Amarildo Tools.",sections:[["Email us","For general questions, feedback, corrections, or tool suggestions, contact us at"],["What to include","Mention the tool name, the values you entered, the result you expected, and the device or browser you used so we can review the issue."]] },
 "editorial-standards":{title:"Editorial and Calculation Standards",description:"See how Amarildo Tools creates, reviews, and maintains useful online tools.",sections:[["Clear purpose","Every indexed page should solve a distinct task. We avoid publishing empty pages or tools that merely repeat another calculator with a different title."],["Transparent methods","Where practical, pages identify the formula, assumptions, units, rounding, and limitations behind a result."],["Review and maintenance","Calculations are tested against known examples. Tools affected by changing tax rates, laws, prices, or standards require dated sources and scheduled review before publication."]]}
} as const;
export function generateStaticParams(){return Object.keys(pages).map(page=>({page}));}
export async function generateMetadata({params}:{params:Promise<{page:string}>}):Promise<Metadata>{const {page}=await params,item=pages[page as keyof typeof pages];return item?{title:item.title+" | Amarildo Tools",description:item.description,alternates:{canonical:"/"+page}}:{}}
export default async function InfoPage({params}:{params:Promise<{page:string}>}){const {page}=await params,item=pages[page as keyof typeof pages];if(!item)notFound();return <main><SiteHeader/><article className="info-page"><span className="kicker">Amarildo Tools</span><h1>{item.title}</h1><p className="info-lead">{item.description}</p>{item.sections.map(([heading,copy])=><section key={heading}><h2>{heading}</h2><p>{copy}{page==="contact"&&heading==="Email us"&&<> <a href="mailto:info@amarildotools.com">info@amarildotools.com</a>.</>}</p></section>)}</article><footer><a className="brand" href="/"><span className="brand-mark"><Percent size={18}/></span><span>amarildo tools</span></a><p><a href="mailto:info@amarildotools.com">info@amarildotools.com</a></p><div className="footer-links"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/disclaimer">Disclaimer</a></div><span>© 2026 Amarildo Tools · Created by <a href="https://amarildoprendi.com/" target="_blank" rel="noopener noreferrer">Amarildo Prendi</a></span></footer></main>}
