"use client";

import { useMemo, useState } from "react";
import { Calculator, ChevronRight, Code2, Hammer, Landmark, Percent, Search, Sparkles, WalletCards } from "lucide-react";
import { toolDefinitions } from "@/lib/tool-data";
import SiteHeader from "@/components/site-header";

const categoryIcons = {Math:Calculator,Everyday:Percent,Finance:Landmark,Business:WalletCards,Construction:Hammer,Converters:Percent,Developer:Code2};
const categories = Object.entries(categoryIcons).map(([name,icon])=>({name,icon,count:toolDefinitions.filter(tool=>tool.category===name).length}));
const accents=["blue","violet","amber","teal","rose","cyan"];
const tools = toolDefinitions.map((tool,i)=>({...tool,desc:tool.short,accent:accents[i%accents.length]}));
const fmt = (value: number) => Number.isFinite(value) ? new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value) : "0";

export default function Home() {
  const [percent, setPercent] = useState("15"); const [number, setNumber] = useState("240"); const [query, setQuery] = useState(""); const [shownCount,setShownCount]=useState(12);
  const result = (Number(percent) / 100) * Number(number);
  const filtered = useMemo(() => tools.filter((tool) => (tool.name + " " + tool.category).toLowerCase().includes(query.toLowerCase())), [query]);
  return <main>
    <SiteHeader/>
    <section className="intro" id="top"><div className="eyebrow"><Sparkles size={14}/> Practical tools, no sign-up</div><h1>One clear answer.<br/><span>Zero busywork.</span></h1><p>Fast, accurate calculators and converters for everyday decisions, business, money, building, and code.</p><div className="search-wrap"><label className="search"><Search size={20}/><input value={query} onChange={(e) => {setQuery(e.target.value);setShownCount(12)}} onKeyDown={(e)=>{if(e.key==="Enter"&&filtered[0])window.location.href="/tools/"+filtered[0].slug}} placeholder="Search calculators and tools…" aria-label="Search calculators and tools"/><kbd>Enter</kbd></label>{query&&<div className="search-results" role="listbox">{filtered.slice(0,8).map(tool=><a href={"/tools/"+tool.slug} key={tool.slug}><span><strong>{tool.name}</strong><small>{tool.category}</small></span><ChevronRight size={17}/></a>)}{filtered.length===0&&<p>No matching tool found. Try a shorter search.</p>}{filtered.length>8&&<a className="all-results" href="#tools">See all {filtered.length} results</a>}</div>}</div><div className="quick-links"><span>Popular:</span><a href="/tools/percentage-calculator">Percentage</a><a href="/tools/loan-payment-calculator">Loan payment</a><a href="/tools/profit-margin-calculator">Margin</a><a href="/tools/length-converter">Unit converter</a></div></section>
    <section className="calculator-shell" id="calculator" aria-labelledby="calculator-title"><div className="calc-copy"><span className="category-pill">Everyday calculator</span><h2 id="calculator-title">What is X% of Y?</h2><p>Enter two numbers. Your answer updates instantly.</p><div className="formula-note"><strong>Formula</strong><span>(percentage ÷ 100) × number</span></div></div><div className="calc-panel"><div className="field-row"><label>Percentage<input inputMode="decimal" value={percent} onChange={(e) => setPercent(e.target.value)} aria-label="Percentage"/></label><span>%</span><span className="of">of</span><label>Number<input inputMode="decimal" value={number} onChange={(e) => setNumber(e.target.value)} aria-label="Number"/></label></div><div className="result"><span>Result</span><strong>{fmt(result)}</strong></div><p className="result-sentence">{percent || "0"}% of {number || "0"} is <b>{fmt(result)}</b>.</p></div></section>
    <section className="browse" id="tools"><div className="section-heading"><div><span className="kicker">Start calculating</span><h2>{query?filtered.length+" matching tools":"Useful tools for real work"}</h2></div><p>Each tool gives a direct answer, explains the method, and works smoothly on any screen.</p></div><div className="tool-grid">{filtered.slice(0,shownCount).map((tool, i) => <article className="tool-card" key={tool.name}><div className={"tool-icon " + tool.accent}><span>{i + 1}</span></div><span className="tool-category">{tool.category}</span><h3>{tool.name}</h3><p>{tool.desc}</p><a className="tool-link" href={"/tools/"+tool.slug}>Use tool<ChevronRight size={17}/></a></article>)}{filtered.length === 0 && <p className="empty">No matching tools yet. Try “finance,” “developer,” or “percentage.”</p>}</div>{shownCount<filtered.length&&<button className="load-more" onClick={()=>setShownCount(x=>x+12)}>Load more calculators <span>{Math.min(12,filtered.length-shownCount)} more</span></button>}</section>
    <section className="category-band" id="categories"><div><span className="kicker">Built to grow</span><h2>A focused library,<br/>organized around you.</h2><p>We group every tool by intent, so the right answer is easy to find—not buried under a list of links.</p></div><div className="category-list">{categories.map(({name,count,icon:Icon}) => <a href={"/categories/"+name.toLowerCase()} key={name}><Icon size={21}/><span><strong>{name}</strong><small>{count} live tools</small></span><ChevronRight size={18}/></a>)}</div></section>
    <section className="trust" id="about"><div><strong>Private by default</strong><span>Your entries stay in your browser.</span></div><div><strong>Transparent math</strong><span>Formulas and assumptions are explained.</span></div><div><strong>Human-first</strong><span>No account walls or clutter.</span></div></section>
    <footer><a className="brand" href="#top"><span className="brand-mark"><Percent size={18}/></span><span>amarildo tools</span></a><p>Clear tools for everyday answers.</p><div className="footer-links"><a href="/about">About</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a><a href="mailto:info@amarildotools.com">info@amarildotools.com</a></div><span>© 2026 Amarildo Tools · Created by <a href="https://amarildoprendi.com/" target="_blank" rel="noopener noreferrer">Amarildo Prendi</a></span></footer>
  </main>;
}
