"use client";
import { useMemo, useState } from "react";

type Item={label:string,value:string};
type Preset={fields:{label:string,default:string,suffix?:string}[];calc:(v:number[])=>Item[]};
const n=(v:string)=>Number(v)||0;
const out=(v:number,d=2)=>Number.isFinite(v)?new Intl.NumberFormat("en-US",{maximumFractionDigits:d}).format(v):"0";
const money=(v:number)=>"$"+out(v);
const gcd=(a:number,b:number):number=>b?gcd(b,a%b):Math.abs(a);

const presets:Record<string,Preset>={
 "percentage-calculator":{fields:[{label:"Percentage",default:"15",suffix:"%"},{label:"Number",default:"240"}],calc:v=>[{label:"Result",value:out(v[0]/100*v[1])}]},
 "loan-payment-calculator":{fields:[{label:"Loan amount",default:"25000",suffix:"$"},{label:"Annual interest",default:"6.5",suffix:"%"},{label:"Term",default:"5",suffix:"years"}],calc:v=>{const r=v[1]/1200,m=v[2]*12,p=r?v[0]*r*(1+r)**m/((1+r)**m-1):v[0]/m;return[{label:"Monthly payment",value:money(p)},{label:"Total interest",value:money(p*m-v[0])},{label:"Total repayment",value:money(p*m)}]}},
 "mortgage-payment-calculator":{fields:[{label:"Mortgage amount",default:"350000",suffix:"$"},{label:"Annual rate",default:"6.25",suffix:"%"},{label:"Term",default:"30",suffix:"years"}],calc:v=>{const r=v[1]/1200,m=v[2]*12,p=r?v[0]*r*(1+r)**m/((1+r)**m-1):v[0]/m;return[{label:"Monthly principal & interest",value:money(p)},{label:"Total interest",value:money(p*m-v[0])}]}},
 "compound-interest-calculator":{fields:[{label:"Starting balance",default:"5000",suffix:"$"},{label:"Monthly contribution",default:"250",suffix:"$"},{label:"Annual return",default:"7",suffix:"%"},{label:"Time",default:"10",suffix:"years"}],calc:v=>{const m=v[3]*12,r=v[2]/1200,total=r?v[0]*(1+r)**m+v[1]*(((1+r)**m-1)/r):v[0]+v[1]*m;return[{label:"Estimated balance",value:money(total)},{label:"Contributions",value:money(v[0]+v[1]*m)},{label:"Estimated growth",value:money(total-v[0]-v[1]*m)}]}},
 "simple-interest-calculator":{fields:[{label:"Principal",default:"10000",suffix:"$"},{label:"Annual rate",default:"5",suffix:"%"},{label:"Time",default:"3",suffix:"years"}],calc:v=>{const i=v[0]*v[1]/100*v[2];return[{label:"Interest",value:money(i)},{label:"Final amount",value:money(v[0]+i)}]}},
 "savings-goal-calculator":{fields:[{label:"Savings goal",default:"20000",suffix:"$"},{label:"Current savings",default:"3500",suffix:"$"},{label:"Time",default:"24",suffix:"months"}],calc:v=>[{label:"Needed each month",value:money(Math.max(0,(v[0]-v[1])/v[2]))},{label:"Amount remaining",value:money(Math.max(0,v[0]-v[1]))}]},
 "debt-to-income-calculator":{fields:[{label:"Monthly debt payments",default:"1500",suffix:"$"},{label:"Gross monthly income",default:"6000",suffix:"$"}],calc:v=>[{label:"Debt-to-income ratio",value:out(v[0]/v[1]*100)+"%"}]},
 "credit-card-payoff-calculator":{fields:[{label:"Card balance",default:"5000",suffix:"$"},{label:"APR",default:"19.9",suffix:"%"},{label:"Monthly payment",default:"200",suffix:"$"}],calc:v=>{let bal=v[0],months=0,interest=0,r=v[1]/1200;while(bal>0&&months<1200){const i=bal*r;interest+=i;bal=bal+i-v[2];months++;if(v[2]<=i)break}return v[2]<=v[0]*r?[{label:"Result",value:"Payment is too low"}]:[{label:"Payoff time",value:months+" months"},{label:"Estimated interest",value:money(interest)}]}},
 "profit-margin-calculator":{fields:[{label:"Cost",default:"100",suffix:"$"},{label:"Selling price",default:"150",suffix:"$"}],calc:v=>{const p=v[1]-v[0];return[{label:"Gross profit",value:money(p)},{label:"Profit margin",value:out(p/v[1]*100)+"%"},{label:"Markup",value:out(p/v[0]*100)+"%"}]}},
 "discount-calculator":{fields:[{label:"Original price",default:"120",suffix:"$"},{label:"Discount",default:"25",suffix:"%"}],calc:v=>[{label:"Sale price",value:money(v[0]*(1-v[1]/100))},{label:"You save",value:money(v[0]*v[1]/100)}]},
 "tip-calculator":{fields:[{label:"Bill amount",default:"85",suffix:"$"},{label:"Tip",default:"20",suffix:"%"},{label:"People",default:"2"}],calc:v=>{const tip=v[0]*v[1]/100,total=v[0]+tip;return[{label:"Tip amount",value:money(tip)},{label:"Total bill",value:money(total)},{label:"Per person",value:money(total/Math.max(1,v[2]))}]}},
 "fraction-to-percentage-calculator":{fields:[{label:"Numerator",default:"3"},{label:"Denominator",default:"8"}],calc:v=>[{label:"Percentage",value:out(v[0]/v[1]*100)+"%"}]},
 "ratio-calculator":{fields:[{label:"First number",default:"24"},{label:"Second number",default:"36"}],calc:v=>{const x=gcd(v[0],v[1])||1;return[{label:"Simplified ratio",value:(v[0]/x)+":"+(v[1]/x)}]}},
 "bmi-calculator":{fields:[{label:"Height",default:"175",suffix:"cm"},{label:"Weight",default:"70",suffix:"kg"}],calc:v=>{const bmi=v[1]/(v[0]/100)**2,cat=bmi<18.5?"Underweight":bmi<25?"Healthy range":bmi<30?"Overweight":"Obesity range";return[{label:"BMI",value:out(bmi,1)},{label:"Screening category",value:cat}]}},
 "concrete-calculator":{fields:[{label:"Length",default:"20",suffix:"ft"},{label:"Width",default:"12",suffix:"ft"},{label:"Thickness",default:"4",suffix:"in"}],calc:v=>{const yd=v[0]*v[1]*(v[2]/12)/27;return[{label:"Concrete volume",value:out(yd)+" yd³"},{label:"With 10% waste",value:out(yd*1.1)+" yd³"}]}},
 "square-footage-calculator":{fields:[{label:"Length",default:"20",suffix:"ft"},{label:"Width",default:"15",suffix:"ft"}],calc:v=>[{label:"Area",value:out(v[0]*v[1])+" ft²"}]},
 "paint-calculator":{fields:[{label:"Wall area",default:"1200",suffix:"ft²"},{label:"Number of coats",default:"2"},{label:"Coverage per gallon",default:"350",suffix:"ft²"}],calc:v=>[{label:"Paint needed",value:out(v[0]*v[1]/v[2])+" gallons"},{label:"Whole gallons to buy",value:Math.ceil(v[0]*v[1]/v[2])+" gallons"}]},
 "flooring-calculator":{fields:[{label:"Length",default:"20",suffix:"ft"},{label:"Width",default:"15",suffix:"ft"},{label:"Waste allowance",default:"10",suffix:"%"}],calc:v=>[{label:"Floor area",value:out(v[0]*v[1])+" ft²"},{label:"Order quantity",value:out(v[0]*v[1]*(1+v[2]/100))+" ft²"}]},
 "roofing-calculator":{fields:[{label:"Building length",default:"40",suffix:"ft"},{label:"Building width",default:"25",suffix:"ft"},{label:"Pitch factor",default:"1.12"}],calc:v=>{const area=v[0]*v[1]*v[2];return[{label:"Estimated roof area",value:out(area)+" ft²"},{label:"Roofing squares",value:out(area/100)}]}},
 "gravel-calculator":{fields:[{label:"Length",default:"30",suffix:"ft"},{label:"Width",default:"12",suffix:"ft"},{label:"Depth",default:"4",suffix:"in"}],calc:v=>{const yd=v[0]*v[1]*(v[2]/12)/27;return[{label:"Gravel volume",value:out(yd)+" yd³"},{label:"With 10% extra",value:out(yd*1.1)+" yd³"}]}},
 "drywall-calculator":{fields:[{label:"Total wall area",default:"1500",suffix:"ft²"},{label:"Sheet width",default:"4",suffix:"ft"},{label:"Sheet length",default:"8",suffix:"ft"}],calc:v=>[{label:"Sheets needed",value:Math.ceil(v[0]/(v[1]*v[2])*1.1)+" sheets"},{label:"Includes",value:"10% waste allowance"}]},
 "roas-calculator":{fields:[{label:"Ad revenue",default:"12000",suffix:"$"},{label:"Ad spend",default:"3000",suffix:"$"}],calc:v=>[{label:"ROAS",value:out(v[0]/v[1])+"×"},{label:"Return percentage",value:out(v[0]/v[1]*100)+"%"}]},
 "cpc-calculator":{fields:[{label:"Advertising cost",default:"1500",suffix:"$"},{label:"Clicks",default:"750"}],calc:v=>[{label:"Average CPC",value:money(v[0]/v[1])}]},
 "cpm-calculator":{fields:[{label:"Advertising cost",default:"1500",suffix:"$"},{label:"Impressions",default:"250000"}],calc:v=>[{label:"CPM",value:money(v[0]/v[1]*1000)}]},
 "ctr-calculator":{fields:[{label:"Clicks",default:"1250"},{label:"Impressions",default:"85000"}],calc:v=>[{label:"Click-through rate",value:out(v[0]/v[1]*100)+"%"}]},
 "conversion-rate-calculator":{fields:[{label:"Conversions",default:"125"},{label:"Visitors or clicks",default:"5000"}],calc:v=>[{label:"Conversion rate",value:out(v[0]/v[1]*100)+"%"}]},
 "break-even-calculator":{fields:[{label:"Fixed costs",default:"25000",suffix:"$"},{label:"Price per unit",default:"80",suffix:"$"},{label:"Variable cost per unit",default:"35",suffix:"$"}],calc:v=>[{label:"Break-even units",value:Math.ceil(v[0]/(v[1]-v[2]))+" units"},{label:"Break-even revenue",value:money(Math.ceil(v[0]/(v[1]-v[2]))*v[1])}]},
 "sales-tax-calculator":{fields:[{label:"Price before tax",default:"100",suffix:"$"},{label:"Tax rate",default:"8.25",suffix:"%"}],calc:v=>[{label:"Sales tax",value:money(v[0]*v[1]/100)},{label:"Total price",value:money(v[0]*(1+v[1]/100))}]},
 "percentage-increase-calculator":{fields:[{label:"Old value",default:"80"},{label:"New value",default:"100"}],calc:v=>[{label:"Percentage increase",value:out((v[1]-v[0])/v[0]*100)+"%"},{label:"Amount increased",value:out(v[1]-v[0])}]},
 "percentage-decrease-calculator":{fields:[{label:"Old value",default:"100"},{label:"New value",default:"75"}],calc:v=>[{label:"Percentage decrease",value:out((v[0]-v[1])/v[0]*100)+"%"},{label:"Amount decreased",value:out(v[0]-v[1])}]},
 "percentage-difference-calculator":{fields:[{label:"First value",default:"80"},{label:"Second value",default:"100"}],calc:v=>[{label:"Percentage difference",value:out(Math.abs(v[0]-v[1])/((v[0]+v[1])/2)*100)+"%"}]},
 "grade-percentage-calculator":{fields:[{label:"Points earned",default:"42"},{label:"Points available",default:"50"}],calc:v=>{const p=v[0]/v[1]*100;return[{label:"Grade percentage",value:out(p)+"%"},{label:"Letter estimate",value:p>=90?"A":p>=80?"B":p>=70?"C":p>=60?"D":"F"}]}},
 "triangle-area-calculator":{fields:[{label:"Base",default:"12"},{label:"Height",default:"8"}],calc:v=>[{label:"Triangle area",value:out(v[0]*v[1]/2)+" square units"}]},
 "circle-calculator":{fields:[{label:"Radius",default:"5"}],calc:v=>[{label:"Area",value:out(Math.PI*v[0]**2)},{label:"Circumference",value:out(2*Math.PI*v[0])},{label:"Diameter",value:out(2*v[0])}]},
 "pythagorean-theorem-calculator":{fields:[{label:"Side A",default:"3"},{label:"Side B",default:"4"}],calc:v=>[{label:"Hypotenuse",value:out(Math.hypot(v[0],v[1]),6)}]},
 "running-pace-calculator":{fields:[{label:"Distance",default:"5",suffix:"miles"},{label:"Hours",default:"0"},{label:"Minutes",default:"45"}],calc:v=>{const mins=v[1]*60+v[2],pace=mins/v[0],whole=Math.floor(pace),sec=Math.round((pace-whole)*60);return[{label:"Pace",value:whole+":"+String(sec).padStart(2,"0")+" per mile"},{label:"Speed",value:out(v[0]/(mins/60))+" mph"}]}},
 "fuel-cost-calculator":{fields:[{label:"Trip distance",default:"350",suffix:"miles"},{label:"Fuel economy",default:"28",suffix:"mpg"},{label:"Fuel price",default:"3.45",suffix:"$/gal"}],calc:v=>[{label:"Fuel needed",value:out(v[0]/v[1])+" gallons"},{label:"Estimated trip cost",value:money(v[0]/v[1]*v[2])}]},
 "fuel-economy-calculator":{fields:[{label:"Distance traveled",default:"320",suffix:"miles"},{label:"Fuel used",default:"11",suffix:"gallons"}],calc:v=>[{label:"Fuel economy",value:out(v[0]/v[1])+" mpg"}]},
 "roi-calculator":{fields:[{label:"Initial investment",default:"10000",suffix:"$"},{label:"Ending value",default:"12500",suffix:"$"}],calc:v=>[{label:"Investment gain",value:money(v[1]-v[0])},{label:"ROI",value:out((v[1]-v[0])/v[0]*100)+"%"}]},
 "apy-calculator":{fields:[{label:"Nominal annual rate",default:"5",suffix:"%"},{label:"Compounds per year",default:"12"}],calc:v=>[{label:"Annual percentage yield",value:out(((1+v[0]/100/v[1])**v[1]-1)*100,4)+"%"}]},
 "inflation-calculator":{fields:[{label:"Current amount",default:"1000",suffix:"$"},{label:"Annual inflation",default:"3",suffix:"%"},{label:"Years",default:"10"}],calc:v=>{const future=v[0]*(1+v[1]/100)**v[2];return[{label:"Equivalent future cost",value:money(future)},{label:"Increase",value:money(future-v[0])}]}},
 "salary-calculator":{fields:[{label:"Pay per period",default:"2500",suffix:"$"},{label:"Pay periods per year",default:"26"}],calc:v=>[{label:"Gross annual salary",value:money(v[0]*v[1])},{label:"Average monthly pay",value:money(v[0]*v[1]/12)}]},
 "hourly-to-salary-calculator":{fields:[{label:"Hourly rate",default:"25",suffix:"$"},{label:"Hours per week",default:"40"},{label:"Working weeks",default:"52"}],calc:v=>[{label:"Weekly pay",value:money(v[0]*v[1])},{label:"Monthly average",value:money(v[0]*v[1]*v[2]/12)},{label:"Annual pay",value:money(v[0]*v[1]*v[2])}]},
 "overtime-pay-calculator":{fields:[{label:"Hourly rate",default:"22",suffix:"$"},{label:"Regular hours",default:"40"},{label:"Overtime hours",default:"8"},{label:"Overtime multiplier",default:"1.5"}],calc:v=>[{label:"Regular pay",value:money(v[0]*v[1])},{label:"Overtime pay",value:money(v[0]*v[2]*v[3])},{label:"Total gross pay",value:money(v[0]*v[1]+v[0]*v[2]*v[3])}]},
 "commission-calculator":{fields:[{label:"Eligible sales",default:"50000",suffix:"$"},{label:"Commission rate",default:"6",suffix:"%"},{label:"Base pay",default:"3000",suffix:"$"}],calc:v=>[{label:"Commission",value:money(v[0]*v[1]/100)},{label:"Total compensation",value:money(v[0]*v[1]/100+v[2])}]},
 "emergency-fund-calculator":{fields:[{label:"Essential monthly expenses",default:"3500",suffix:"$"},{label:"Months of coverage",default:"6"},{label:"Current emergency savings",default:"5000",suffix:"$"}],calc:v=>[{label:"Target emergency fund",value:money(v[0]*v[1])},{label:"Still needed",value:money(Math.max(0,v[0]*v[1]-v[2]))}]},
 "retirement-withdrawal-calculator":{fields:[{label:"Portfolio balance",default:"500000",suffix:"$"},{label:"Annual withdrawal rate",default:"4",suffix:"%"}],calc:v=>[{label:"Annual withdrawal",value:money(v[0]*v[1]/100)},{label:"Monthly withdrawal",value:money(v[0]*v[1]/1200)}]},
 "board-foot-calculator":{fields:[{label:"Thickness",default:"2",suffix:"in"},{label:"Width",default:"8",suffix:"in"},{label:"Length",default:"10",suffix:"ft"},{label:"Quantity",default:"12"}],calc:v=>[{label:"Total board feet",value:out(v[0]*v[1]*v[2]/12*v[3])}]},
 "mulch-calculator":{fields:[{label:"Length",default:"30",suffix:"ft"},{label:"Width",default:"12",suffix:"ft"},{label:"Depth",default:"3",suffix:"in"}],calc:v=>[{label:"Mulch needed",value:out(v[0]*v[1]*v[2]/324)+" yd³"},{label:"Rounded order",value:Math.ceil(v[0]*v[1]*v[2]/324*2)/2+" yd³"}]},
 "tile-calculator":{fields:[{label:"Project area",default:"240",suffix:"ft²"},{label:"Tile length",default:"12",suffix:"in"},{label:"Tile width",default:"12",suffix:"in"},{label:"Waste",default:"10",suffix:"%"}],calc:v=>{const count=v[0]/(v[1]*v[2]/144)*(1+v[3]/100);return[{label:"Tiles needed",value:Math.ceil(count)+" tiles"}]}},
 "brick-calculator":{fields:[{label:"Wall area",default:"300",suffix:"ft²"},{label:"Bricks per square foot",default:"7"},{label:"Waste",default:"5",suffix:"%"}],calc:v=>[{label:"Bricks needed",value:Math.ceil(v[0]*v[1]*(1+v[2]/100))+" bricks"}]},
 "fence-calculator":{fields:[{label:"Fence length",default:"160",suffix:"ft"},{label:"Panel width",default:"8",suffix:"ft"}],calc:v=>{const panels=Math.ceil(v[0]/v[1]);return[{label:"Fence panels",value:panels+" panels"},{label:"Posts",value:panels+1+" posts"}]}},
 "decking-calculator":{fields:[{label:"Deck width",default:"16",suffix:"ft"},{label:"Board effective width",default:"5.5",suffix:"in"},{label:"Deck length",default:"20",suffix:"ft"}],calc:v=>{const boards=Math.ceil(v[0]*12/v[1]*1.1);return[{label:"Deck boards",value:boards+" boards"},{label:"Board length",value:out(v[2])+" ft each"},{label:"Includes",value:"10% waste"}]}},
 "asphalt-calculator":{fields:[{label:"Length",default:"100",suffix:"ft"},{label:"Width",default:"20",suffix:"ft"},{label:"Depth",default:"3",suffix:"in"}],calc:v=>{const ft3=v[0]*v[1]*v[2]/12,tons=ft3*145/2000;return[{label:"Asphalt volume",value:out(ft3/27)+" yd³"},{label:"Estimated weight",value:out(tons)+" tons"}]}},
 "customer-acquisition-cost-calculator":{fields:[{label:"Marketing and sales spend",default:"25000",suffix:"$"},{label:"New customers",default:"500"}],calc:v=>[{label:"Customer acquisition cost",value:money(v[0]/v[1])}]},
 "customer-lifetime-value-calculator":{fields:[{label:"Average purchase",default:"80",suffix:"$"},{label:"Purchases per year",default:"6"},{label:"Customer lifespan",default:"4",suffix:"years"},{label:"Gross margin",default:"45",suffix:"%"}],calc:v=>[{label:"Estimated customer LTV",value:money(v[0]*v[1]*v[2]*v[3]/100)},{label:"Gross revenue value",value:money(v[0]*v[1]*v[2])}]},
 "churn-rate-calculator":{fields:[{label:"Customers at start",default:"1000"},{label:"Customers lost",default:"45"}],calc:v=>[{label:"Churn rate",value:out(v[1]/v[0]*100)+"%"},{label:"Retention rate",value:out((1-v[1]/v[0])*100)+"%"}]},
 "weighted-average-calculator":{fields:[{label:"First value",default:"80"},{label:"First weight",default:"40",suffix:"%"},{label:"Second value",default:"95"},{label:"Second weight",default:"60",suffix:"%"}],calc:v=>[{label:"Weighted average",value:out((v[0]*v[1]+v[2]*v[3])/(v[1]+v[3]))}]},
 "margin-of-error-calculator":{fields:[{label:"Sample size",default:"1000"},{label:"Expected proportion",default:"50",suffix:"%"},{label:"Z-score",default:"1.96"}],calc:v=>{const p=v[1]/100,moe=v[2]*Math.sqrt(p*(1-p)/v[0])*100;return[{label:"Margin of error",value:"±"+out(moe)+"%"},{label:"Approximate interval",value:out(v[1]-moe)+"% to "+out(v[1]+moe)+"%"}]}},
 "z-score-calculator":{fields:[{label:"Observed value",default:"85"},{label:"Mean",default:"70"},{label:"Standard deviation",default:"10"}],calc:v=>[{label:"Z-score",value:out((v[0]-v[1])/v[2],4)}]},
 "permutation-calculator":{fields:[{label:"Total items (n)",default:"10"},{label:"Selected items (r)",default:"3"}],calc:v=>{let x=1;for(let i=0;i<v[1];i++)x*=v[0]-i;return[{label:"Permutations",value:out(x,0)}]}},
 "combination-calculator":{fields:[{label:"Total items (n)",default:"10"},{label:"Selected items (r)",default:"3"}],calc:v=>{let x=1;for(let i=1;i<=v[1];i++)x=x*(v[0]-v[1]+i)/i;return[{label:"Combinations",value:out(x,0)}]}},
 "factorial-calculator":{fields:[{label:"Whole number",default:"8"}],calc:v=>{let x=1;for(let i=2;i<=Math.floor(v[0]);i++)x*=i;return[{label:"Factorial",value:out(x,0)}]}},
 "exponent-calculator":{fields:[{label:"Base",default:"5"},{label:"Exponent",default:"3"}],calc:v=>[{label:"Result",value:out(v[0]**v[1],8)}]},
 "square-root-calculator":{fields:[{label:"Number",default:"144"}],calc:v=>[{label:"Square root",value:v[0]<0?"No real-number result":out(Math.sqrt(v[0]),8)}]},
 "net-worth-calculator":{fields:[{label:"Total assets",default:"250000",suffix:"$"},{label:"Total liabilities",default:"125000",suffix:"$"}],calc:v=>[{label:"Net worth",value:money(v[0]-v[1])}]},
 "monthly-cash-flow-calculator":{fields:[{label:"Monthly take-home income",default:"6500",suffix:"$"},{label:"Monthly expenses",default:"4800",suffix:"$"}],calc:v=>[{label:"Monthly cash flow",value:money(v[0]-v[1])},{label:"Cash flow rate",value:out((v[0]-v[1])/v[0]*100)+"%"}]},
 "loan-to-value-calculator":{fields:[{label:"Loan amount",default:"280000",suffix:"$"},{label:"Property value",default:"350000",suffix:"$"}],calc:v=>[{label:"Loan-to-value ratio",value:out(v[0]/v[1]*100)+"%"},{label:"Estimated equity",value:money(v[1]-v[0])}]},
 "down-payment-calculator":{fields:[{label:"Purchase price",default:"350000",suffix:"$"},{label:"Down payment rate",default:"20",suffix:"%"}],calc:v=>[{label:"Down payment",value:money(v[0]*v[1]/100)},{label:"Loan amount",value:money(v[0]*(1-v[1]/100))}]},
 "rent-affordability-calculator":{fields:[{label:"Gross monthly income",default:"6000",suffix:"$"},{label:"Housing budget rate",default:"30",suffix:"%"}],calc:v=>[{label:"Estimated rent budget",value:money(v[0]*v[1]/100)},{label:"Income remaining",value:money(v[0]*(1-v[1]/100))}]},
 "savings-rate-calculator":{fields:[{label:"Monthly savings",default:"1200",suffix:"$"},{label:"Take-home income",default:"6000",suffix:"$"}],calc:v=>[{label:"Savings rate",value:out(v[0]/v[1]*100)+"%"},{label:"Annual savings",value:money(v[0]*12)}]},
 "dividend-yield-calculator":{fields:[{label:"Annual dividend per share",default:"3.20",suffix:"$"},{label:"Share price",default:"80",suffix:"$"},{label:"Shares owned",default:"100"}],calc:v=>[{label:"Dividend yield",value:out(v[0]/v[1]*100)+"%"},{label:"Estimated annual income",value:money(v[0]*v[2])}]},
 "rule-of-72-calculator":{fields:[{label:"Annual return rate",default:"8",suffix:"%"}],calc:v=>[{label:"Estimated doubling time",value:out(72/v[0])+" years"}]},
 "room-volume-calculator":{fields:[{label:"Length",default:"16",suffix:"ft"},{label:"Width",default:"12",suffix:"ft"},{label:"Height",default:"9",suffix:"ft"}],calc:v=>[{label:"Room volume",value:out(v[0]*v[1]*v[2])+" ft³"},{label:"Floor area",value:out(v[0]*v[1])+" ft²"}]},
 "wallpaper-calculator":{fields:[{label:"Wall perimeter",default:"56",suffix:"ft"},{label:"Wall height",default:"9",suffix:"ft"},{label:"Openings",default:"70",suffix:"ft²"},{label:"Coverage per roll",default:"56",suffix:"ft²"}],calc:v=>{const area=Math.max(0,v[0]*v[1]-v[2]);return[{label:"Wallpaper area",value:out(area)+" ft²"},{label:"Rolls with 10% extra",value:Math.ceil(area*1.1/v[3])+" rolls"}]}},
 "topsoil-calculator":{fields:[{label:"Length",default:"30",suffix:"ft"},{label:"Width",default:"20",suffix:"ft"},{label:"Depth",default:"4",suffix:"in"}],calc:v=>{const yd=v[0]*v[1]*v[2]/324;return[{label:"Topsoil volume",value:out(yd)+" yd³"},{label:"With 10% extra",value:out(yd*1.1)+" yd³"}]}},
 "sand-calculator":{fields:[{label:"Length",default:"20",suffix:"ft"},{label:"Width",default:"12",suffix:"ft"},{label:"Depth",default:"3",suffix:"in"}],calc:v=>{const yd=v[0]*v[1]*v[2]/324;return[{label:"Sand volume",value:out(yd)+" yd³"},{label:"Approximate weight",value:out(yd*1.35)+" tons"}]}},
 "siding-calculator":{fields:[{label:"Total wall area",default:"1800",suffix:"ft²"},{label:"Doors and windows",default:"220",suffix:"ft²"},{label:"Waste",default:"10",suffix:"%"}],calc:v=>{const net=Math.max(0,v[0]-v[1]);return[{label:"Net wall area",value:out(net)+" ft²"},{label:"Siding to order",value:out(net*(1+v[2]/100))+" ft²"}]}},
 "insulation-calculator":{fields:[{label:"Area to insulate",default:"1200",suffix:"ft²"},{label:"Coverage per package",default:"40",suffix:"ft²"},{label:"Waste",default:"10",suffix:"%"}],calc:v=>[{label:"Packages needed",value:Math.ceil(v[0]*(1+v[2]/100)/v[1])+" packages"}]},
 "wall-stud-calculator":{fields:[{label:"Wall length",default:"24",suffix:"ft"},{label:"Stud spacing",default:"16",suffix:"in"}],calc:v=>[{label:"Basic stud count",value:Math.ceil(v[0]*12/v[1])+1+" studs"},{label:"With 15% extra",value:Math.ceil((Math.ceil(v[0]*12/v[1])+1)*1.15)+" studs"}]},
 "average-order-value-calculator":{fields:[{label:"Total revenue",default:"85000",suffix:"$"},{label:"Number of orders",default:"1250"}],calc:v=>[{label:"Average order value",value:money(v[0]/v[1])}]},
 "cart-abandonment-rate-calculator":{fields:[{label:"Shopping carts created",default:"5000"},{label:"Completed purchases",default:"1450"}],calc:v=>[{label:"Cart abandonment rate",value:out((v[0]-v[1])/v[0]*100)+"%"},{label:"Cart conversion rate",value:out(v[1]/v[0]*100)+"%"}]},
 "gross-profit-calculator":{fields:[{label:"Revenue",default:"125000",suffix:"$"},{label:"Cost of goods sold",default:"68000",suffix:"$"}],calc:v=>[{label:"Gross profit",value:money(v[0]-v[1])},{label:"Gross margin",value:out((v[0]-v[1])/v[0]*100)+"%"}]},
 "quadratic-formula-calculator":{fields:[{label:"Coefficient a",default:"1"},{label:"Coefficient b",default:"-5"},{label:"Coefficient c",default:"6"}],calc:v=>{const disc=v[1]**2-4*v[0]*v[2];if(!v[0])return[{label:"Result",value:"Coefficient a cannot be zero"}];if(disc<0){const real=-v[1]/(2*v[0]),imag=Math.sqrt(-disc)/Math.abs(2*v[0]);return[{label:"First root",value:out(real)+" + "+out(imag)+"i"},{label:"Second root",value:out(real)+" − "+out(imag)+"i"}]}return[{label:"First root",value:out((-v[1]+Math.sqrt(disc))/(2*v[0]),8)},{label:"Second root",value:out((-v[1]-Math.sqrt(disc))/(2*v[0]),8)}]}},
 "slope-calculator":{fields:[{label:"x₁",default:"1"},{label:"y₁",default:"2"},{label:"x₂",default:"5"},{label:"y₂",default:"10"}],calc:v=>[{label:"Slope",value:v[2]===v[0]?"Undefined (vertical line)":out((v[3]-v[1])/(v[2]-v[0]),8)}]},
 "distance-between-points-calculator":{fields:[{label:"x₁",default:"1"},{label:"y₁",default:"2"},{label:"x₂",default:"5"},{label:"y₂",default:"5"}],calc:v=>[{label:"Distance",value:out(Math.hypot(v[2]-v[0],v[3]-v[1]),8)}]},
 "midpoint-calculator":{fields:[{label:"x₁",default:"1"},{label:"y₁",default:"2"},{label:"x₂",default:"5"},{label:"y₂",default:"8"}],calc:v=>[{label:"Midpoint",value:"("+out((v[0]+v[2])/2)+", "+out((v[1]+v[3])/2)+")"}]},
 "linear-equation-calculator":{fields:[{label:"Slope (m)",default:"3"},{label:"x",default:"4"},{label:"Y-intercept (b)",default:"2"}],calc:v=>[{label:"y",value:out(v[0]*v[1]+v[2])}]},
 "absolute-value-calculator":{fields:[{label:"Number",default:"-42"}],calc:v=>[{label:"Absolute value",value:out(Math.abs(v[0]))}]},
 "logarithm-calculator":{fields:[{label:"Positive number",default:"1000"},{label:"Logarithm base",default:"10"}],calc:v=>[{label:"Logarithm",value:v[0]>0&&v[1]>0&&v[1]!==1?out(Math.log(v[0])/Math.log(v[1]),10):"Enter a valid number and base"}]},
 "natural-log-calculator":{fields:[{label:"Positive number",default:"20"}],calc:v=>[{label:"Natural logarithm",value:v[0]>0?out(Math.log(v[0]),10):"Enter a positive number"}]},
 "cube-root-calculator":{fields:[{label:"Number",default:"125"}],calc:v=>[{label:"Cube root",value:out(Math.cbrt(v[0]),10)}]},
 "nth-root-calculator":{fields:[{label:"Number",default:"256"},{label:"Root",default:"4"}],calc:v=>[{label:"Nth root",value:v[1]&&!(v[0]<0&&v[1]%2===0)?out(Math.sign(v[0])*Math.abs(v[0])**(1/v[1]),10):"No real-number result"}]},
 "prime-number-calculator":{fields:[{label:"Whole number",default:"97"}],calc:v=>{const x=Math.floor(v[0]);let prime=x>=2;for(let i=2;i<=Math.sqrt(x)&&prime;i++)if(x%i===0)prime=false;return[{label:"Result",value:prime?x+" is prime":x+" is not prime"}]}},
 "prime-factorization-calculator":{fields:[{label:"Whole number",default:"360"}],calc:v=>{let x=Math.abs(Math.floor(v[0])),d=2;const factors:number[]=[];while(x>1&&d<=Math.sqrt(x)){while(x%d===0){factors.push(d);x/=d}d++}if(x>1)factors.push(x);return[{label:"Prime factors",value:factors.length?factors.join(" × "):"No prime factors"}]}},
 "least-common-multiple-calculator":{fields:[{label:"First integer",default:"24"},{label:"Second integer",default:"36"}],calc:v=>[{label:"Least common multiple",value:out(Math.abs(v[0]*v[1])/(gcd(v[0],v[1])||1),0)}]},
 "greatest-common-factor-calculator":{fields:[{label:"First integer",default:"84"},{label:"Second integer",default:"126"}],calc:v=>[{label:"Greatest common factor",value:out(gcd(v[0],v[1]),0)}]},
 "modulo-calculator":{fields:[{label:"Dividend",default:"29"},{label:"Divisor",default:"6"}],calc:v=>[{label:"Remainder",value:v[1]?out(((v[0]%v[1])+v[1])%v[1]):"Divisor cannot be zero"}]},
 "fraction-simplifier":{fields:[{label:"Numerator",default:"42"},{label:"Denominator",default:"56"}],calc:v=>{const g=gcd(v[0],v[1])||1;return[{label:"Simplified fraction",value:(v[0]/g)+"/"+(v[1]/g)}]}},
 "decimal-to-fraction-calculator":{fields:[{label:"Decimal",default:"0.625"}],calc:v=>{const raw=String(v[0]),digits=(raw.split(".")[1]||"").length,den=10**digits,num=Math.round(v[0]*den),g=gcd(num,den)||1;return[{label:"Fraction",value:(num/g)+"/"+(den/g)}]}},
 "adding-fractions-calculator":{fields:[{label:"First numerator",default:"1"},{label:"First denominator",default:"3"},{label:"Second numerator",default:"1"},{label:"Second denominator",default:"4"}],calc:v=>{const num=v[0]*v[3]+v[2]*v[1],den=v[1]*v[3],g=gcd(num,den)||1;return[{label:"Sum",value:(num/g)+"/"+(den/g)}]}},
 "multiplying-fractions-calculator":{fields:[{label:"First numerator",default:"2"},{label:"First denominator",default:"3"},{label:"Second numerator",default:"3"},{label:"Second denominator",default:"5"}],calc:v=>{const num=v[0]*v[2],den=v[1]*v[3],g=gcd(num,den)||1;return[{label:"Product",value:(num/g)+"/"+(den/g)}]}},
 "arithmetic-sequence-calculator":{fields:[{label:"First term",default:"3"},{label:"Common difference",default:"5"},{label:"Term number (n)",default:"10"}],calc:v=>{const term=v[0]+(v[2]-1)*v[1],sum=v[2]/2*(2*v[0]+(v[2]-1)*v[1]);return[{label:"Nth term",value:out(term)},{label:"Sum through nth term",value:out(sum)}]}},
 "rectangle-calculator":{fields:[{label:"Length",default:"12"},{label:"Width",default:"8"}],calc:v=>[{label:"Area",value:out(v[0]*v[1])+" square units"},{label:"Perimeter",value:out(2*(v[0]+v[1]))+" units"},{label:"Diagonal",value:out(Math.hypot(v[0],v[1]),8)+" units"}]},
 "trapezoid-area-calculator":{fields:[{label:"First parallel base",default:"10"},{label:"Second parallel base",default:"16"},{label:"Height",default:"7"}],calc:v=>[{label:"Area",value:out((v[0]+v[1])*v[2]/2)+" square units"}]},
 "parallelogram-area-calculator":{fields:[{label:"Base",default:"12"},{label:"Perpendicular height",default:"8"},{label:"Side length",default:"9"}],calc:v=>[{label:"Area",value:out(v[0]*v[1])+" square units"},{label:"Perimeter",value:out(2*(v[0]+v[2]))+" units"}]},
 "sphere-calculator":{fields:[{label:"Radius",default:"6"}],calc:v=>[{label:"Volume",value:out(4/3*Math.PI*v[0]**3,8)+" cubic units"},{label:"Surface area",value:out(4*Math.PI*v[0]**2,8)+" square units"}]},
 "cylinder-calculator":{fields:[{label:"Radius",default:"5"},{label:"Height",default:"12"}],calc:v=>[{label:"Volume",value:out(Math.PI*v[0]**2*v[1],8)+" cubic units"},{label:"Surface area",value:out(2*Math.PI*v[0]*(v[0]+v[1]),8)+" square units"}]},
 "cone-calculator":{fields:[{label:"Radius",default:"5"},{label:"Height",default:"12"}],calc:v=>{const slant=Math.hypot(v[0],v[1]);return[{label:"Volume",value:out(Math.PI*v[0]**2*v[1]/3,8)+" cubic units"},{label:"Slant height",value:out(slant,8)+" units"},{label:"Surface area",value:out(Math.PI*v[0]*(v[0]+slant),8)+" square units"}]}},
 "rectangular-prism-calculator":{fields:[{label:"Length",default:"10"},{label:"Width",default:"6"},{label:"Height",default:"4"}],calc:v=>[{label:"Volume",value:out(v[0]*v[1]*v[2])+" cubic units"},{label:"Surface area",value:out(2*(v[0]*v[1]+v[0]*v[2]+v[1]*v[2]))+" square units"}]},
 "polygon-interior-angle-calculator":{fields:[{label:"Number of sides",default:"8"}],calc:v=>[{label:"Interior angle sum",value:out((v[0]-2)*180)+"°"},{label:"Each angle if regular",value:out((v[0]-2)*180/v[0])+"°"},{label:"Exterior angle if regular",value:out(360/v[0])+"°"}]},
 "recipe-scaling-calculator":{fields:[{label:"Original ingredient amount",default:"2",suffix:"cups"},{label:"Original servings",default:"4"},{label:"Desired servings",default:"10"}],calc:v=>[{label:"Scaled ingredient amount",value:out(v[0]*v[2]/v[1])+" cups"},{label:"Scale factor",value:out(v[2]/v[1])+"×"}]},
 "unit-price-calculator":{fields:[{label:"Package price",default:"18.99",suffix:"$"},{label:"Quantity",default:"24"}],calc:v=>[{label:"Price per unit",value:money(v[0]/v[1])}]},
 "price-per-square-foot-calculator":{fields:[{label:"Total price",default:"425000",suffix:"$"},{label:"Total area",default:"2100",suffix:"ft²"}],calc:v=>[{label:"Price per square foot",value:money(v[0]/v[1])}]},
 "split-bill-calculator":{fields:[{label:"Subtotal",default:"120",suffix:"$"},{label:"Tax",default:"8.25",suffix:"%"},{label:"Tip",default:"20",suffix:"%"},{label:"People",default:"4"}],calc:v=>{const tax=v[0]*v[1]/100,tip=v[0]*v[2]/100,total=v[0]+tax+tip;return[{label:"Total bill",value:money(total)},{label:"Per person",value:money(total/Math.max(1,v[3]))},{label:"Tax and tip",value:money(tax+tip)}]}},
 "cagr-calculator":{fields:[{label:"Beginning value",default:"10000",suffix:"$"},{label:"Ending value",default:"18000",suffix:"$"},{label:"Years",default:"5"}],calc:v=>[{label:"Compound annual growth rate",value:out(((v[1]/v[0])**(1/v[2])-1)*100,4)+"%"}]},
 "future-value-calculator":{fields:[{label:"Present value",default:"10000",suffix:"$"},{label:"Annual rate",default:"7",suffix:"%"},{label:"Years",default:"10"}],calc:v=>[{label:"Future value",value:money(v[0]*(1+v[1]/100)**v[2])},{label:"Growth",value:money(v[0]*(1+v[1]/100)**v[2]-v[0])}]},
 "present-value-calculator":{fields:[{label:"Future value",default:"20000",suffix:"$"},{label:"Annual discount rate",default:"6",suffix:"%"},{label:"Years",default:"8"}],calc:v=>[{label:"Present value",value:money(v[0]/(1+v[1]/100)**v[2])}]},
 "effective-annual-rate-calculator":{fields:[{label:"Nominal annual rate",default:"6",suffix:"%"},{label:"Compounding periods",default:"12"}],calc:v=>[{label:"Effective annual rate",value:out(((1+v[0]/100/v[1])**v[1]-1)*100,6)+"%"}]},
 "investment-fee-calculator":{fields:[{label:"Starting investment",default:"50000",suffix:"$"},{label:"Annual return",default:"7",suffix:"%"},{label:"Annual fee",default:"1",suffix:"%"},{label:"Years",default:"20"}],calc:v=>{const before=v[0]*(1+v[1]/100)**v[3],after=v[0]*(1+(v[1]-v[2])/100)**v[3];return[{label:"Value before fees",value:money(before)},{label:"Estimated value after fees",value:money(after)},{label:"Estimated fee impact",value:money(before-after)}]}},
 "debt-payment-ratio-calculator":{fields:[{label:"Monthly debt payments",default:"1200",suffix:"$"},{label:"Monthly take-home income",default:"5200",suffix:"$"}],calc:v=>[{label:"Debt payment ratio",value:out(v[0]/v[1]*100)+"%"},{label:"Income after debt payments",value:money(v[1]-v[0])}]},
 "revenue-growth-calculator":{fields:[{label:"Previous revenue",default:"95000",suffix:"$"},{label:"Current revenue",default:"118000",suffix:"$"}],calc:v=>[{label:"Revenue growth",value:out((v[1]-v[0])/v[0]*100)+"%"},{label:"Revenue change",value:money(v[1]-v[0])}]},
 "inventory-turnover-calculator":{fields:[{label:"Cost of goods sold",default:"500000",suffix:"$"},{label:"Beginning inventory",default:"90000",suffix:"$"},{label:"Ending inventory",default:"110000",suffix:"$"}],calc:v=>{const avg=(v[1]+v[2])/2,turn=v[0]/avg;return[{label:"Inventory turnover",value:out(turn)+"×"},{label:"Average inventory",value:money(avg)},{label:"Approximate days in inventory",value:out(365/turn)+" days"}]}},
 "freelance-rate-calculator":{fields:[{label:"Annual income goal",default:"80000",suffix:"$"},{label:"Annual business expenses",default:"15000",suffix:"$"},{label:"Billable hours per year",default:"1200"}],calc:v=>[{label:"Minimum hourly rate",value:money((v[0]+v[1])/v[2])},{label:"Monthly revenue target",value:money((v[0]+v[1])/12)}]},
 "excavation-calculator":{fields:[{label:"Length",default:"40",suffix:"ft"},{label:"Width",default:"20",suffix:"ft"},{label:"Depth",default:"4",suffix:"ft"}],calc:v=>{const ft3=v[0]*v[1]*v[2];return[{label:"Excavation volume",value:out(ft3)+" ft³"},{label:"Cubic yards",value:out(ft3/27)+" yd³"}]}},
 "paver-calculator":{fields:[{label:"Project area",default:"500",suffix:"ft²"},{label:"Paver length",default:"8",suffix:"in"},{label:"Paver width",default:"4",suffix:"in"},{label:"Waste",default:"10",suffix:"%"}],calc:v=>{const area=v[1]*v[2]/144,count=v[0]/area*(1+v[3]/100);return[{label:"Pavers needed",value:Math.ceil(count)+" pavers"},{label:"Includes",value:out(v[3])+"% waste"}]}},
 "pool-volume-calculator":{fields:[{label:"Pool length",default:"30",suffix:"ft"},{label:"Pool width",default:"15",suffix:"ft"},{label:"Average depth",default:"5",suffix:"ft"}],calc:v=>[{label:"Pool volume",value:out(v[0]*v[1]*v[2]*7.48052)+" gallons"},{label:"Cubic feet",value:out(v[0]*v[1]*v[2])+" ft³"}]},
 "stair-calculator":{fields:[{label:"Total rise",default:"108",suffix:"in"},{label:"Target riser height",default:"7.5",suffix:"in"}],calc:v=>{const risers=Math.max(1,Math.round(v[0]/v[1]));return[{label:"Number of risers",value:risers+" risers"},{label:"Actual riser height",value:out(v[0]/risers,3)+" in"},{label:"Approximate treads",value:Math.max(0,risers-1)+" treads"}]}},
 "acos-calculator":{fields:[{label:"Ad spend",default:"2500",suffix:"$"},{label:"Attributed ad sales",default:"10000",suffix:"$"}],calc:v=>[{label:"ACoS",value:out(v[0]/v[1]*100)+"%"},{label:"ROAS",value:out(v[1]/v[0])+"×"}]},
 "tacos-calculator":{fields:[{label:"Ad spend",default:"2500",suffix:"$"},{label:"Total sales",default:"18000",suffix:"$"}],calc:v=>[{label:"TACoS",value:out(v[0]/v[1]*100)+"%"},{label:"Sales after ad spend",value:money(v[1]-v[0])}]},
 "marketing-efficiency-ratio-calculator":{fields:[{label:"Total revenue",default:"125000",suffix:"$"},{label:"Total marketing spend",default:"25000",suffix:"$"}],calc:v=>[{label:"Marketing efficiency ratio",value:out(v[0]/v[1])+"×"},{label:"Marketing cost percentage",value:out(v[1]/v[0]*100)+"%"}]},
 "break-even-acos-calculator":{fields:[{label:"Selling price",default:"40",suffix:"$"},{label:"Product and fulfillment cost",default:"24",suffix:"$"}],calc:v=>[{label:"Pre-ad profit",value:money(v[0]-v[1])},{label:"Break-even ACoS",value:out((v[0]-v[1])/v[0]*100)+"%"},{label:"Break-even ad spend per sale",value:money(v[0]-v[1])}]},
 "ppc-profit-calculator":{fields:[{label:"Attributed ad sales",default:"15000",suffix:"$"},{label:"Product and fulfillment costs",default:"8500",suffix:"$"},{label:"Ad spend",default:"3200",suffix:"$"}],calc:v=>{const p=v[0]-v[1]-v[2];return[{label:"Estimated PPC profit",value:money(p)},{label:"Profit margin",value:out(p/v[0]*100)+"%"},{label:"ACoS",value:out(v[2]/v[0]*100)+"%"}]}},
 "contribution-margin-calculator":{fields:[{label:"Selling price",default:"80",suffix:"$"},{label:"Variable cost",default:"45",suffix:"$"}],calc:v=>[{label:"Contribution per unit",value:money(v[0]-v[1])},{label:"Contribution margin",value:out((v[0]-v[1])/v[0]*100)+"%"}]},
 "target-cpa-calculator":{fields:[{label:"Average order value",default:"120",suffix:"$"},{label:"Contribution margin",default:"35",suffix:"%"}],calc:v=>[{label:"Maximum break-even CPA",value:money(v[0]*v[1]/100)},{label:"Revenue remaining before acquisition",value:money(v[0]*(1-v[1]/100))}]},
 "cost-per-lead-calculator":{fields:[{label:"Campaign spend",default:"5000",suffix:"$"},{label:"Leads generated",default:"250"}],calc:v=>[{label:"Cost per lead",value:money(v[0]/v[1])}]},
 "lead-to-customer-rate-calculator":{fields:[{label:"New customers",default:"42"},{label:"Total leads",default:"300"}],calc:v=>[{label:"Lead-to-customer rate",value:out(v[0]/v[1]*100)+"%"},{label:"Leads per customer",value:out(v[1]/v[0])}]},
 "email-open-rate-calculator":{fields:[{label:"Unique opens",default:"4200"},{label:"Delivered emails",default:"15000"}],calc:v=>[{label:"Email open rate",value:out(v[0]/v[1]*100)+"%"}]},
 "email-click-rate-calculator":{fields:[{label:"Unique clicks",default:"850"},{label:"Delivered emails",default:"15000"}],calc:v=>[{label:"Email click rate",value:out(v[0]/v[1]*100)+"%"},{label:"Click-to-open rate",value:"Add opens for CTOR analysis"}]},
 "email-unsubscribe-rate-calculator":{fields:[{label:"Unsubscribes",default:"32"},{label:"Delivered emails",default:"15000"}],calc:v=>[{label:"Unsubscribe rate",value:out(v[0]/v[1]*100,4)+"%"}]},
 "website-bounce-rate-calculator":{fields:[{label:"Bounced sessions",default:"4200"},{label:"Total sessions",default:"10000"}],calc:v=>[{label:"Bounce rate",value:out(v[0]/v[1]*100)+"%"},{label:"Non-bounce rate",value:out((1-v[0]/v[1])*100)+"%"}]},
 "social-engagement-rate-calculator":{fields:[{label:"Total interactions",default:"1850"},{label:"Reach or followers",default:"50000"}],calc:v=>[{label:"Engagement rate",value:out(v[0]/v[1]*100,3)+"%"}]},
 "follower-growth-rate-calculator":{fields:[{label:"Starting followers",default:"25000"},{label:"New followers",default:"1800"},{label:"Lost followers",default:"300"}],calc:v=>[{label:"Net follower growth",value:out(v[1]-v[2],0)},{label:"Growth rate",value:out((v[1]-v[2])/v[0]*100,3)+"%"}]},
 "revenue-per-visitor-calculator":{fields:[{label:"Website revenue",default:"85000",suffix:"$"},{label:"Visitors",default:"50000"}],calc:v=>[{label:"Revenue per visitor",value:money(v[0]/v[1])}]},
 "revenue-per-employee-calculator":{fields:[{label:"Annual revenue",default:"2500000",suffix:"$"},{label:"Employees",default:"25"}],calc:v=>[{label:"Revenue per employee",value:money(v[0]/v[1])}]},
 "repeat-purchase-rate-calculator":{fields:[{label:"Repeat customers",default:"1800"},{label:"Total customers",default:"8000"}],calc:v=>[{label:"Repeat purchase rate",value:out(v[0]/v[1]*100)+"%"},{label:"First-time customer share",value:out((1-v[0]/v[1])*100)+"%"}]},
 "refund-rate-calculator":{fields:[{label:"Refunded orders",default:"85"},{label:"Total orders",default:"5000"}],calc:v=>[{label:"Refund rate",value:out(v[0]/v[1]*100,3)+"%"},{label:"Orders kept",value:out(v[1]-v[0],0)}]},
 "product-return-rate-calculator":{fields:[{label:"Returned units",default:"120"},{label:"Units sold",default:"6500"}],calc:v=>[{label:"Product return rate",value:out(v[0]/v[1]*100,3)+"%"},{label:"Units retained",value:out(v[1]-v[0],0)}]},
 "days-in-inventory-calculator":{fields:[{label:"Average inventory",default:"120000",suffix:"$"},{label:"Annual cost of goods sold",default:"900000",suffix:"$"},{label:"Days in period",default:"365"}],calc:v=>[{label:"Days in inventory",value:out(v[0]/v[1]*v[2])+" days"},{label:"Inventory turnover",value:out(v[1]/v[0])+"×"}]},
 "sell-through-rate-calculator":{fields:[{label:"Units sold",default:"4200"},{label:"Beginning inventory plus receipts",default:"6000"}],calc:v=>[{label:"Sell-through rate",value:out(v[0]/v[1]*100)+"%"},{label:"Units remaining",value:out(v[1]-v[0],0)}]},
 "ad-frequency-calculator":{fields:[{label:"Impressions",default:"750000"},{label:"Reach",default:"250000"}],calc:v=>[{label:"Average frequency",value:out(v[0]/v[1])+" exposures per person"}]},
 "impression-share-calculator":{fields:[{label:"Impressions received",default:"450000"},{label:"Estimated eligible impressions",default:"600000"}],calc:v=>[{label:"Impression share",value:out(v[0]/v[1]*100)+"%"},{label:"Missed impression share",value:out((1-v[0]/v[1])*100)+"%"}]},
 "campaign-budget-pacing-calculator":{fields:[{label:"Total campaign budget",default:"30000",suffix:"$"},{label:"Campaign days",default:"30"},{label:"Days elapsed",default:"12"},{label:"Actual spend so far",default:"13500",suffix:"$"}],calc:v=>{const expected=v[0]*v[2]/v[1],variance=v[3]-expected;return[{label:"Expected spend to date",value:money(expected)},{label:"Pacing variance",value:(variance>=0?"+":"")+money(variance)},{label:"Budget remaining",value:money(v[0]-v[3])}]}},
 "subtracting-fractions-calculator":{fields:[{label:"First numerator",default:"5"},{label:"First denominator",default:"6"},{label:"Second numerator",default:"1"},{label:"Second denominator",default:"4"}],calc:v=>{if(!v[1]||!v[3])return[{label:"Difference",value:"Denominators cannot be zero"}];const num=v[0]*v[3]-v[2]*v[1],den=v[1]*v[3],g=gcd(num,den)||1;return[{label:"Difference",value:(num/g)+"/"+(den/g)}]}},
 "dividing-fractions-calculator":{fields:[{label:"First numerator",default:"2"},{label:"First denominator",default:"3"},{label:"Second numerator",default:"4"},{label:"Second denominator",default:"5"}],calc:v=>{if(!v[1]||!v[2]||!v[3])return[{label:"Quotient",value:"Cannot divide by zero"}];const num=v[0]*v[3],den=v[1]*v[2],g=gcd(num,den)||1;return[{label:"Quotient",value:(num/g)+"/"+(den/g)}]}},
 "proportion-calculator":{fields:[{label:"First value (a)",default:"4"},{label:"Second value (b)",default:"10"},{label:"Third value (c)",default:"14"}],calc:v=>[{label:"Missing value (x)",value:v[0]?out(v[1]*v[2]/v[0],8):"First value cannot be zero"}]},
 "mixed-number-calculator":{fields:[{label:"Numerator",default:"17"},{label:"Denominator",default:"5"}],calc:v=>{if(!v[1])return[{label:"Mixed number",value:"Denominator cannot be zero"}];const whole=Math.trunc(v[0]/v[1]),rem=Math.abs(v[0]%v[1]),g=gcd(rem,v[1])||1;return[{label:"Mixed number",value:rem?whole+" "+rem/g+"/"+Math.abs(v[1]/g):String(whole)}]}},
 "scientific-notation-calculator":{fields:[{label:"Number",default:"1250000"}],calc:v=>[{label:"Scientific notation",value:v[0]?v[0].toExponential(8).replace(/\.0+e/,"e").replace(/e\+?(-?\d+)/," × 10^$1"):"0"}]},
 "rounding-calculator":{fields:[{label:"Number",default:"12.34567"},{label:"Decimal places",default:"2"}],calc:v=>{const d=Math.max(0,Math.min(12,Math.floor(v[1]))),f=10**d;return[{label:"Rounded value",value:(Math.round((v[0]+Number.EPSILON)*f)/f).toFixed(d)}]}},
 "significant-figures-calculator":{fields:[{label:"Number",default:"12345.678"},{label:"Significant figures",default:"4"}],calc:v=>{const s=Math.max(1,Math.min(15,Math.floor(v[1])));return[{label:"Rounded value",value:v[0]?Number(v[0].toPrecision(s)).toString():"0"}]}},
 "quadratic-discriminant-calculator":{fields:[{label:"Coefficient a",default:"1"},{label:"Coefficient b",default:"-5"},{label:"Coefficient c",default:"6"}],calc:v=>{const d=v[1]**2-4*v[0]*v[2];return[{label:"Discriminant",value:out(d,8)},{label:"Root type",value:d>0?"Two distinct real roots":d===0?"One repeated real root":"Two complex roots"}]}},
 "two-variable-equation-calculator":{fields:[{label:"a₁",default:"2"},{label:"b₁",default:"3"},{label:"c₁",default:"13"},{label:"a₂",default:"4"},{label:"b₂",default:"-1"},{label:"c₂",default:"5"}],calc:v=>{const d=v[0]*v[4]-v[3]*v[1];return d?[{label:"x",value:out((v[2]*v[4]-v[5]*v[1])/d,8)},{label:"y",value:out((v[0]*v[5]-v[3]*v[2])/d,8)}]:[{label:"Result",value:"No unique solution"}]}},
 "matrix-determinant-calculator":{fields:[{label:"Top left (a)",default:"3"},{label:"Top right (b)",default:"8"},{label:"Bottom left (c)",default:"4"},{label:"Bottom right (d)",default:"6"}],calc:v=>[{label:"Determinant",value:out(v[0]*v[3]-v[1]*v[2],8)}]},
 "right-triangle-calculator":{fields:[{label:"Leg a",default:"3"},{label:"Leg b",default:"4"}],calc:v=>{const h=Math.hypot(v[0],v[1]);return[{label:"Hypotenuse",value:out(h,8)},{label:"Area",value:out(v[0]*v[1]/2)+" square units"},{label:"Perimeter",value:out(v[0]+v[1]+h,8)+" units"}]}},
 "triangle-perimeter-calculator":{fields:[{label:"Side a",default:"5"},{label:"Side b",default:"7"},{label:"Side c",default:"9"}],calc:v=>{const valid=v[0]+v[1]>v[2]&&v[0]+v[2]>v[1]&&v[1]+v[2]>v[0];return[{label:"Perimeter",value:valid?out(v[0]+v[1]+v[2])+" units":"Invalid triangle"},{label:"Triangle check",value:valid?"These sides form a triangle":"Two sides must exceed the third"}]}},
 "ellipse-area-calculator":{fields:[{label:"Semi-major axis (a)",default:"8"},{label:"Semi-minor axis (b)",default:"5"}],calc:v=>[{label:"Area",value:out(Math.PI*v[0]*v[1],8)+" square units"}]},
 "sector-area-calculator":{fields:[{label:"Radius",default:"10"},{label:"Central angle",default:"60",suffix:"degrees"}],calc:v=>[{label:"Sector area",value:out(v[1]/360*Math.PI*v[0]**2,8)+" square units"}]},
 "arc-length-calculator":{fields:[{label:"Radius",default:"10"},{label:"Central angle",default:"90",suffix:"degrees"}],calc:v=>[{label:"Arc length",value:out(v[1]/360*2*Math.PI*v[0],8)+" units"}]},
 "regular-polygon-area-calculator":{fields:[{label:"Number of sides",default:"6"},{label:"Side length",default:"8"}],calc:v=>{const sides=Math.max(3,Math.floor(v[0]));return[{label:"Area",value:out(sides*v[1]**2/(4*Math.tan(Math.PI/sides)),8)+" square units"},{label:"Perimeter",value:out(sides*v[1])+" units"}]}},
 "geometric-sequence-calculator":{fields:[{label:"First term",default:"3"},{label:"Common ratio",default:"2"},{label:"Term number (n)",default:"8"}],calc:v=>{const count=Math.max(1,Math.floor(v[2])),term=v[0]*v[1]**(count-1),sum=v[1]===1?v[0]*count:v[0]*(1-v[1]**count)/(1-v[1]);return[{label:"Nth term",value:out(term,8)},{label:"Sum through nth term",value:out(sum,8)}]}},
 "mean-absolute-deviation-calculator":{fields:[{label:"Value 1",default:"4"},{label:"Value 2",default:"7"},{label:"Value 3",default:"8"},{label:"Value 4",default:"10"},{label:"Value 5",default:"11"}],calc:v=>{const mean=v.reduce((a,b)=>a+b,0)/v.length,mad=v.reduce((a,b)=>a+Math.abs(b-mean),0)/v.length;return[{label:"Mean",value:out(mean,8)},{label:"Mean absolute deviation",value:out(mad,8)}]}},
 "probability-calculator":{fields:[{label:"Favorable outcomes",default:"3"},{label:"Total outcomes",default:"10"}],calc:v=>{if(v[1]<=0||v[0]<0||v[0]>v[1])return[{label:"Result",value:"Enter valid outcome counts"}];const p=v[0]/v[1];return[{label:"Probability",value:out(p,8)},{label:"Percentage",value:out(p*100,4)+"%"},{label:"Complement",value:out((1-p)*100,4)+"%"}]}},
 "odds-probability-converter":{fields:[{label:"Odds for",default:"3"},{label:"Odds against",default:"2"}],calc:v=>{const total=v[0]+v[1];return[{label:"Probability",value:total>0?out(v[0]/total,8):"Enter positive odds"},{label:"Percentage",value:total>0?out(v[0]/total*100,4)+"%":"—"}]}},
 "cube-calculator":{fields:[{label:"Side length",default:"6"}],calc:v=>[{label:"Volume",value:out(v[0]**3)+" cubic units"},{label:"Surface area",value:out(6*v[0]**2)+" square units"},{label:"Space diagonal",value:out(v[0]*Math.sqrt(3),8)+" units"}]},
 "square-calculator":{fields:[{label:"Side length",default:"8"}],calc:v=>[{label:"Area",value:out(v[0]**2)+" square units"},{label:"Perimeter",value:out(4*v[0])+" units"},{label:"Diagonal",value:out(v[0]*Math.sqrt(2),8)+" units"}]},
 "percent-error-calculator":{fields:[{label:"Observed value",default:"98"},{label:"Accepted value",default:"100"}],calc:v=>[{label:"Absolute error",value:out(Math.abs(v[0]-v[1]),8)},{label:"Percent error",value:v[1]?out(Math.abs(v[0]-v[1])/Math.abs(v[1])*100,6)+"%":"Accepted value cannot be zero"}]},
 "herons-formula-calculator":{fields:[{label:"Side a",default:"5"},{label:"Side b",default:"6"},{label:"Side c",default:"7"}],calc:v=>{const s=(v[0]+v[1]+v[2])/2,area=Math.sqrt(Math.max(0,s*(s-v[0])*(s-v[1])*(s-v[2]))),valid=v[0]+v[1]>v[2]&&v[0]+v[2]>v[1]&&v[1]+v[2]>v[0];return[{label:"Area",value:valid?out(area,8)+" square units":"Invalid triangle"},{label:"Semiperimeter",value:out(s)+" units"}]}},
 "law-of-cosines-calculator":{fields:[{label:"Side a",default:"8"},{label:"Side b",default:"10"},{label:"Included angle C",default:"60",suffix:"degrees"}],calc:v=>{const c=Math.sqrt(v[0]**2+v[1]**2-2*v[0]*v[1]*Math.cos(v[2]*Math.PI/180));return[{label:"Side c",value:out(c,8)+" units"}]}},
 "law-of-sines-calculator":{fields:[{label:"Known side a",default:"10"},{label:"Opposite angle A",default:"45",suffix:"degrees"},{label:"Target angle B",default:"60",suffix:"degrees"}],calc:v=>[{label:"Side b",value:Math.sin(v[1]*Math.PI/180)?out(v[0]*Math.sin(v[2]*Math.PI/180)/Math.sin(v[1]*Math.PI/180),8)+" units":"Angle A is invalid"}]},
 "three-dimensional-distance-calculator":{fields:[{label:"x₁",default:"1"},{label:"y₁",default:"2"},{label:"z₁",default:"3"},{label:"x₂",default:"5"},{label:"y₂",default:"7"},{label:"z₂",default:"9"}],calc:v=>[{label:"3D distance",value:out(Math.hypot(v[3]-v[0],v[4]-v[1],v[5]-v[2]),8)}]},
 "annulus-area-calculator":{fields:[{label:"Outer radius",default:"10"},{label:"Inner radius",default:"6"}],calc:v=>[{label:"Annulus area",value:v[0]>=v[1]?out(Math.PI*(v[0]**2-v[1]**2),8)+" square units":"Outer radius must be larger"}]},
 "sector-perimeter-calculator":{fields:[{label:"Radius",default:"8"},{label:"Central angle",default:"75",suffix:"degrees"}],calc:v=>{const arc=v[1]/360*2*Math.PI*v[0];return[{label:"Arc length",value:out(arc,8)+" units"},{label:"Sector perimeter",value:out(2*v[0]+arc,8)+" units"}]}},
 "expected-value-calculator":{fields:[{label:"First outcome",default:"100"},{label:"First probability",default:"40",suffix:"%"},{label:"Second outcome",default:"20"},{label:"Second probability",default:"60",suffix:"%"}],calc:v=>[{label:"Expected value",value:out(v[0]*v[1]/100+v[2]*v[3]/100,8)},{label:"Probability total",value:out(v[1]+v[3])+"%"}]},
 "coefficient-of-variation-calculator":{fields:[{label:"Mean",default:"50"},{label:"Standard deviation",default:"8"}],calc:v=>[{label:"Coefficient of variation",value:v[0]?out(Math.abs(v[1]/v[0])*100,6)+"%":"Mean cannot be zero"}]},
 "standard-error-calculator":{fields:[{label:"Sample standard deviation",default:"12"},{label:"Sample size",default:"64"}],calc:v=>[{label:"Standard error",value:v[1]>0?out(v[0]/Math.sqrt(v[1]),8):"Sample size must be positive"}]},
 "sample-size-calculator":{fields:[{label:"Confidence Z-score",default:"1.96"},{label:"Expected proportion",default:"50",suffix:"%"},{label:"Margin of error",default:"5",suffix:"%"}],calc:v=>{const p=v[1]/100,e=v[2]/100;return[{label:"Minimum sample size",value:e>0?Math.ceil(v[0]**2*p*(1-p)/e**2).toLocaleString():"Margin of error must be positive"}]}},
 "midrange-calculator":{fields:[{label:"Minimum value",default:"12"},{label:"Maximum value",default:"48"}],calc:v=>[{label:"Midrange",value:out((v[0]+v[1])/2,8)},{label:"Range",value:out(v[1]-v[0],8)}]},
 "aspect-ratio-calculator":{fields:[{label:"Width",default:"1920"},{label:"Height",default:"1080"}],calc:v=>{const g=gcd(v[0],v[1])||1;return[{label:"Simplified ratio",value:v[1]?v[0]/g+":"+v[1]/g:"Height cannot be zero"},{label:"Decimal ratio",value:v[1]?out(v[0]/v[1],6):"—"}]}},
 "screen-resolution-scaler":{fields:[{label:"Original width",default:"1920"},{label:"Original height",default:"1080"},{label:"New width",default:"1280"}],calc:v=>[{label:"New height",value:v[0]?out(v[1]*v[2]/v[0],0)+" px":"Original width cannot be zero"},{label:"Scale",value:v[0]?out(v[2]/v[0]*100,2)+"%":"—"}]},
 "px-to-rem-calculator":{fields:[{label:"Pixels",default:"24",suffix:"px"},{label:"Root font size",default:"16",suffix:"px"}],calc:v=>[{label:"REM",value:v[1]?out(v[0]/v[1],6)+" rem":"Root size cannot be zero"},{label:"Pixels",value:out(v[0])+" px"}]},
 "css-clamp-calculator":{fields:[{label:"Minimum size",default:"16",suffix:"px"},{label:"Base size",default:"14",suffix:"px"},{label:"Viewport factor",default:"1.5",suffix:"vw"},{label:"Maximum size",default:"32",suffix:"px"},{label:"Viewport width",default:"1200",suffix:"px"}],calc:v=>{const preferred=v[1]+v[2]*v[4]/100,result=Math.min(v[3],Math.max(v[0],preferred));return[{label:"Preferred size",value:out(preferred,3)+" px"},{label:"Clamped result",value:out(result,3)+" px"}]}},
 "download-time-calculator":{fields:[{label:"File size",default:"500",suffix:"MB"},{label:"Connection speed",default:"100",suffix:"Mbps"}],calc:v=>{const sec=v[1]?v[0]*8/v[1]:0;return[{label:"Download time",value:v[1]?out(sec,2)+" seconds":"Speed cannot be zero"},{label:"Minutes",value:v[1]?out(sec/60,2)+" minutes":"—"}]}},
 "api-rate-limit-calculator":{fields:[{label:"Requests per interval",default:"1000"},{label:"Interval length",default:"60",suffix:"seconds"},{label:"Period",default:"24",suffix:"hours"}],calc:v=>[{label:"Period capacity",value:v[1]?out(v[0]*v[2]*3600/v[1],0)+" requests":"Interval cannot be zero"},{label:"Average requests per second",value:v[1]?out(v[0]/v[1],3):"—"}]},
 "database-storage-calculator":{fields:[{label:"Records",default:"1000000"},{label:"Average record size",default:"1200",suffix:"bytes"},{label:"Index overhead",default:"25",suffix:"%"}],calc:v=>{const bytes=v[0]*v[1]*(1+v[2]/100);return[{label:"Estimated storage",value:out(bytes/1e9,4)+" GB"},{label:"Megabytes",value:out(bytes/1e6,2)+" MB"}]}},
 "image-file-size-calculator":{fields:[{label:"Width",default:"3840",suffix:"px"},{label:"Height",default:"2160",suffix:"px"},{label:"Color depth",default:"24",suffix:"bits"}],calc:v=>{const bytes=v[0]*v[1]*v[2]/8;return[{label:"Uncompressed size",value:out(bytes/1e6,3)+" MB"},{label:"Pixels",value:out(v[0]*v[1],0)}]}},
 "video-file-size-calculator":{fields:[{label:"Video bitrate",default:"8",suffix:"Mbps"},{label:"Duration",default:"10",suffix:"minutes"}],calc:v=>[{label:"Estimated file size",value:out(v[0]*v[1]*60/8,2)+" MB"},{label:"Gigabytes",value:out(v[0]*v[1]*60/8000,4)+" GB"}]},
 "audio-file-size-calculator":{fields:[{label:"Sample rate",default:"44100",suffix:"Hz"},{label:"Bit depth",default:"16",suffix:"bits"},{label:"Channels",default:"2"},{label:"Duration",default:"5",suffix:"minutes"}],calc:v=>{const bytes=v[0]*v[1]*v[2]*v[3]*60/8;return[{label:"Uncompressed size",value:out(bytes/1e6,2)+" MB"}]}},
 "grid-column-width-calculator":{fields:[{label:"Container width",default:"1200",suffix:"px"},{label:"Columns",default:"12"},{label:"Gap",default:"24",suffix:"px"}],calc:v=>{const cols=Math.max(1,Math.floor(v[1]));return[{label:"Column width",value:out((v[0]-(cols-1)*v[2])/cols,3)+" px"},{label:"Total gap width",value:out((cols-1)*v[2])+" px"}]}},
 "cache-hit-rate-calculator":{fields:[{label:"Cache hits",default:"85000"},{label:"Cache misses",default:"15000"}],calc:v=>{const total=v[0]+v[1];return[{label:"Cache hit rate",value:total?out(v[0]/total*100,3)+"%":"No requests"},{label:"Miss rate",value:total?out(v[1]/total*100,3)+"%":"—"}]}},
 "server-capacity-calculator":{fields:[{label:"Requests per second",default:"500"},{label:"Average response time",default:"250",suffix:"ms"},{label:"Safety margin",default:"20",suffix:"%"}],calc:v=>{const concurrent=v[0]*v[1]/1000;return[{label:"Estimated concurrency",value:out(concurrent,2)+" requests"},{label:"Recommended capacity",value:out(concurrent*(1+v[2]/100),2)+" requests"}]}},
 "uptime-calculator":{fields:[{label:"Total period",default:"30",suffix:"days"},{label:"Downtime",default:"45",suffix:"minutes"}],calc:v=>{const total=v[0]*1440;return[{label:"Uptime",value:total?out((total-v[1])/total*100,6)+"%":"Period must be positive"},{label:"Available minutes",value:out(Math.max(0,total-v[1]),0)}]}},
 "availability-downtime-calculator":{fields:[{label:"Availability target",default:"99.9",suffix:"%"},{label:"Period",default:"30",suffix:"days"}],calc:v=>{const mins=v[1]*1440*(1-v[0]/100);return[{label:"Allowed downtime",value:out(mins,3)+" minutes"},{label:"Hours",value:out(mins/60,4)+" hours"}]}},
 "data-transfer-cost-calculator":{fields:[{label:"Transfer volume",default:"2500",suffix:"GB"},{label:"Price per GB",default:"0.08",suffix:"$"},{label:"Free allowance",default:"100",suffix:"GB"}],calc:v=>{const billable=Math.max(0,v[0]-v[2]);return[{label:"Billable transfer",value:out(billable)+" GB"},{label:"Estimated cost",value:money(billable*v[1])}]}},
 "concurrent-users-calculator":{fields:[{label:"Visits",default:"100000"},{label:"Average visit duration",default:"4",suffix:"minutes"},{label:"Period",default:"24",suffix:"hours"}],calc:v=>[{label:"Average concurrent users",value:v[2]?out(v[0]*v[1]/(v[2]*60),2):"Period cannot be zero"}]},
 "requests-per-second-calculator":{fields:[{label:"Total requests",default:"5000000"},{label:"Elapsed time",default:"2",suffix:"hours"}],calc:v=>[{label:"Average RPS",value:v[1]?out(v[0]/(v[1]*3600),3):"Time cannot be zero"},{label:"Requests per minute",value:v[1]?out(v[0]/(v[1]*60),2):"—"}]},
 "compression-ratio-calculator":{fields:[{label:"Original size",default:"100",suffix:"MB"},{label:"Compressed size",default:"28",suffix:"MB"}],calc:v=>[{label:"Compression ratio",value:v[1]?out(v[0]/v[1],3)+":1":"Compressed size cannot be zero"},{label:"Size reduction",value:v[0]?out((v[0]-v[1])/v[0]*100,3)+"%":"—"}]},
 "responsive-breakpoint-calculator":{fields:[{label:"Minimum width",default:"320",suffix:"px"},{label:"Maximum width",default:"1440",suffix:"px"},{label:"Intervals",default:"4"}],calc:v=>{const steps=Math.max(1,Math.floor(v[2]));return[{label:"Breakpoint step",value:out((v[1]-v[0])/steps,2)+" px"},{label:"First breakpoint",value:out(v[0]+(v[1]-v[0])/steps,2)+" px"}]}},
 "sum-of-squares-calculator":{fields:[{label:"Value 1",default:"2"},{label:"Value 2",default:"3"},{label:"Value 3",default:"4"},{label:"Value 4",default:"5"},{label:"Value 5",default:"6"}],calc:v=>[{label:"Sum of squares",value:out(v.reduce((a,b)=>a+b*b,0),8)}]},
 "difference-of-squares-calculator":{fields:[{label:"Value a",default:"12"},{label:"Value b",default:"5"}],calc:v=>[{label:"Difference of squares",value:out(v[0]**2-v[1]**2,8)},{label:"Factored values",value:"("+out(v[0]-v[1])+") × ("+out(v[0]+v[1])+")"}]},
 "reciprocal-calculator":{fields:[{label:"Number",default:"8"}],calc:v=>[{label:"Reciprocal",value:v[0]?out(1/v[0],12):"Zero has no reciprocal"}]},
 "power-of-ten-calculator":{fields:[{label:"Exponent",default:"6"}],calc:v=>[{label:"Result",value:out(10**v[0],12)},{label:"Scientific notation",value:"1 × 10^"+v[0]}]},
 "degrees-to-radians-calculator":{fields:[{label:"Degrees",default:"180",suffix:"°"}],calc:v=>[{label:"Radians",value:out(v[0]*Math.PI/180,12)},{label:"In terms of π",value:out(v[0]/180,8)+"π"}]},
 "radians-to-degrees-calculator":{fields:[{label:"Radians",default:"3.14159265"}],calc:v=>[{label:"Degrees",value:out(v[0]*180/Math.PI,10)+"°"}]},
 "sine-calculator":{fields:[{label:"Angle",default:"30",suffix:"degrees"}],calc:v=>[{label:"Sine",value:out(Math.sin(v[0]*Math.PI/180),12)}]},
 "cosine-calculator":{fields:[{label:"Angle",default:"60",suffix:"degrees"}],calc:v=>[{label:"Cosine",value:out(Math.cos(v[0]*Math.PI/180),12)}]},
 "tangent-calculator":{fields:[{label:"Angle",default:"45",suffix:"degrees"}],calc:v=>[{label:"Tangent",value:out(Math.tan(v[0]*Math.PI/180),12)}]},
 "inverse-sine-calculator":{fields:[{label:"Sine value",default:"0.5"}],calc:v=>[{label:"Angle",value:Math.abs(v[0])<=1?out(Math.asin(v[0])*180/Math.PI,10)+"°":"Value must be between −1 and 1"}]},
 "inverse-cosine-calculator":{fields:[{label:"Cosine value",default:"0.5"}],calc:v=>[{label:"Angle",value:Math.abs(v[0])<=1?out(Math.acos(v[0])*180/Math.PI,10)+"°":"Value must be between −1 and 1"}]},
 "inverse-tangent-calculator":{fields:[{label:"Tangent value",default:"1"}],calc:v=>[{label:"Angle",value:out(Math.atan(v[0])*180/Math.PI,10)+"°"}]},
 "pentagon-area-calculator":{fields:[{label:"Side length",default:"7"}],calc:v=>[{label:"Area",value:out(.25*Math.sqrt(5*(5+2*Math.sqrt(5)))*v[0]**2,8)+" square units"},{label:"Perimeter",value:out(5*v[0])+" units"}]},
 "hexagon-area-calculator":{fields:[{label:"Side length",default:"7"}],calc:v=>[{label:"Area",value:out(3*Math.sqrt(3)/2*v[0]**2,8)+" square units"},{label:"Perimeter",value:out(6*v[0])+" units"}]},
 "octagon-area-calculator":{fields:[{label:"Side length",default:"7"}],calc:v=>[{label:"Area",value:out(2*(1+Math.sqrt(2))*v[0]**2,8)+" square units"},{label:"Perimeter",value:out(8*v[0])+" units"}]},
 "rhombus-area-calculator":{fields:[{label:"First diagonal",default:"12"},{label:"Second diagonal",default:"8"}],calc:v=>[{label:"Area",value:out(v[0]*v[1]/2)+" square units"}]},
 "kite-area-calculator":{fields:[{label:"First diagonal",default:"15"},{label:"Second diagonal",default:"10"}],calc:v=>[{label:"Area",value:out(v[0]*v[1]/2)+" square units"}]},
 "semicircle-calculator":{fields:[{label:"Radius",default:"8"}],calc:v=>[{label:"Area",value:out(Math.PI*v[0]**2/2,8)+" square units"},{label:"Perimeter",value:out(Math.PI*v[0]+2*v[0],8)+" units"}]},
 "hemisphere-calculator":{fields:[{label:"Radius",default:"6"}],calc:v=>[{label:"Volume",value:out(2/3*Math.PI*v[0]**3,8)+" cubic units"},{label:"Curved surface area",value:out(2*Math.PI*v[0]**2,8)+" square units"},{label:"Total surface area",value:out(3*Math.PI*v[0]**2,8)+" square units"}]},
 "pyramid-volume-calculator":{fields:[{label:"Base length",default:"10"},{label:"Base width",default:"8"},{label:"Height",default:"12"}],calc:v=>[{label:"Volume",value:out(v[0]*v[1]*v[2]/3,8)+" cubic units"}]},
 "triangular-prism-calculator":{fields:[{label:"Triangle base",default:"8"},{label:"Triangle height",default:"6"},{label:"Prism length",default:"15"}],calc:v=>[{label:"Volume",value:out(v[0]*v[1]/2*v[2],8)+" cubic units"},{label:"Base area",value:out(v[0]*v[1]/2)+" square units"}]},
 "population-density-calculator":{fields:[{label:"Population",default:"250000"},{label:"Area",default:"125",suffix:"km²"}],calc:v=>[{label:"Population density",value:v[1]?out(v[0]/v[1],3)+" people per km²":"Area cannot be zero"}]},
 "relative-change-calculator":{fields:[{label:"Original value",default:"80"},{label:"New value",default:"100"}],calc:v=>[{label:"Relative change",value:v[0]?out((v[1]-v[0])/Math.abs(v[0])*100,4)+"%":"Original value cannot be zero"},{label:"Absolute change",value:out(v[1]-v[0])}]},
 "weighted-percentage-calculator":{fields:[{label:"Score 1",default:"85"},{label:"Weight 1",default:"30",suffix:"%"},{label:"Score 2",default:"92"},{label:"Weight 2",default:"30",suffix:"%"},{label:"Score 3",default:"78"},{label:"Weight 3",default:"40",suffix:"%"}],calc:v=>{const w=v[1]+v[3]+v[5];return[{label:"Weighted result",value:w?out((v[0]*v[1]+v[2]*v[3]+v[4]*v[5])/w,4):"Weights cannot total zero"},{label:"Weight total",value:out(w)+"%"}]}},
 "pooled-mean-calculator":{fields:[{label:"First group mean",default:"72"},{label:"First group size",default:"30"},{label:"Second group mean",default:"81"},{label:"Second group size",default:"45"}],calc:v=>[{label:"Pooled mean",value:v[1]+v[3]?out((v[0]*v[1]+v[2]*v[3])/(v[1]+v[3]),8):"Group sizes cannot total zero"}]},
 "variance-from-standard-deviation-calculator":{fields:[{label:"Standard deviation",default:"12"}],calc:v=>[{label:"Variance",value:out(v[0]**2,10)}]},
 "standard-deviation-from-variance-calculator":{fields:[{label:"Variance",default:"144"}],calc:v=>[{label:"Standard deviation",value:v[0]>=0?out(Math.sqrt(v[0]),10):"Variance cannot be negative"}]},
 "z-score-to-value-calculator":{fields:[{label:"Z-score",default:"1.5"},{label:"Mean",default:"70"},{label:"Standard deviation",default:"10"}],calc:v=>[{label:"Raw value",value:out(v[1]+v[0]*v[2],8)}]},
 "relative-frequency-calculator":{fields:[{label:"Event count",default:"42"},{label:"Total observations",default:"120"}],calc:v=>[{label:"Relative frequency",value:v[1]?out(v[0]/v[1],8):"Total cannot be zero"},{label:"Percentage",value:v[1]?out(v[0]/v[1]*100,4)+"%":"—"}]},
 "population-growth-calculator":{fields:[{label:"Current population",default:"100000"},{label:"Annual growth rate",default:"2.5",suffix:"%"},{label:"Years",default:"10"}],calc:v=>{const future=v[0]*(1+v[1]/100)**v[2];return[{label:"Projected population",value:out(future,0)},{label:"Total growth",value:out(future-v[0],0)}]}},
};

const metricPresets:Record<string,Preset>={
 "concrete-calculator":{fields:[{label:"Length",default:"6",suffix:"m"},{label:"Width",default:"4",suffix:"m"},{label:"Thickness",default:"10",suffix:"cm"}],calc:v=>{const m3=v[0]*v[1]*v[2]/100;return[{label:"Concrete volume",value:out(m3)+" m³"},{label:"With 10% waste",value:out(m3*1.1)+" m³"}]}},
 "square-footage-calculator":{fields:[{label:"Length",default:"6",suffix:"m"},{label:"Width",default:"4",suffix:"m"}],calc:v=>[{label:"Area",value:out(v[0]*v[1])+" m²"}]},
 "paint-calculator":{fields:[{label:"Wall area",default:"110",suffix:"m²"},{label:"Number of coats",default:"2"},{label:"Coverage per liter",default:"10",suffix:"m²"}],calc:v=>[{label:"Paint needed",value:out(v[0]*v[1]/v[2])+" liters"},{label:"Whole liters to buy",value:Math.ceil(v[0]*v[1]/v[2])+" liters"}]},
 "flooring-calculator":{fields:[{label:"Length",default:"6",suffix:"m"},{label:"Width",default:"4",suffix:"m"},{label:"Waste allowance",default:"10",suffix:"%"}],calc:v=>[{label:"Floor area",value:out(v[0]*v[1])+" m²"},{label:"Order quantity",value:out(v[0]*v[1]*(1+v[2]/100))+" m²"}]},
 "roofing-calculator":{fields:[{label:"Building length",default:"12",suffix:"m"},{label:"Building width",default:"8",suffix:"m"},{label:"Pitch factor",default:"1.12"}],calc:v=>[{label:"Estimated roof area",value:out(v[0]*v[1]*v[2])+" m²"},{label:"With 10% extra",value:out(v[0]*v[1]*v[2]*1.1)+" m²"}]},
 "gravel-calculator":{fields:[{label:"Length",default:"9",suffix:"m"},{label:"Width",default:"4",suffix:"m"},{label:"Depth",default:"10",suffix:"cm"}],calc:v=>{const m3=v[0]*v[1]*v[2]/100;return[{label:"Gravel volume",value:out(m3)+" m³"},{label:"With 10% extra",value:out(m3*1.1)+" m³"}]}},
 "mulch-calculator":{fields:[{label:"Length",default:"9",suffix:"m"},{label:"Width",default:"4",suffix:"m"},{label:"Depth",default:"8",suffix:"cm"}],calc:v=>{const m3=v[0]*v[1]*v[2]/100;return[{label:"Mulch needed",value:out(m3)+" m³"},{label:"Rounded order",value:Math.ceil(m3*10)/10+" m³"}]}},
 "topsoil-calculator":{fields:[{label:"Length",default:"9",suffix:"m"},{label:"Width",default:"6",suffix:"m"},{label:"Depth",default:"10",suffix:"cm"}],calc:v=>{const m3=v[0]*v[1]*v[2]/100;return[{label:"Topsoil volume",value:out(m3)+" m³"},{label:"With 10% extra",value:out(m3*1.1)+" m³"}]}},
 "sand-calculator":{fields:[{label:"Length",default:"6",suffix:"m"},{label:"Width",default:"4",suffix:"m"},{label:"Depth",default:"8",suffix:"cm"}],calc:v=>{const m3=v[0]*v[1]*v[2]/100;return[{label:"Sand volume",value:out(m3)+" m³"},{label:"Approximate weight",value:out(m3*1.6)+" tonnes"}]}},
 "room-volume-calculator":{fields:[{label:"Length",default:"5",suffix:"m"},{label:"Width",default:"4",suffix:"m"},{label:"Height",default:"2.6",suffix:"m"}],calc:v=>[{label:"Room volume",value:out(v[0]*v[1]*v[2])+" m³"},{label:"Floor area",value:out(v[0]*v[1])+" m²"}]},
 "wallpaper-calculator":{fields:[{label:"Wall perimeter",default:"17",suffix:"m"},{label:"Wall height",default:"2.7",suffix:"m"},{label:"Openings",default:"6.5",suffix:"m²"},{label:"Coverage per roll",default:"5.2",suffix:"m²"}],calc:v=>{const area=Math.max(0,v[0]*v[1]-v[2]);return[{label:"Wallpaper area",value:out(area)+" m²"},{label:"Rolls with 10% extra",value:Math.ceil(area*1.1/v[3])+" rolls"}]}},
 "siding-calculator":{fields:[{label:"Total wall area",default:"170",suffix:"m²"},{label:"Doors and windows",default:"20",suffix:"m²"},{label:"Waste",default:"10",suffix:"%"}],calc:v=>{const net=Math.max(0,v[0]-v[1]);return[{label:"Net wall area",value:out(net)+" m²"},{label:"Siding to order",value:out(net*(1+v[2]/100))+" m²"}]}},
 "insulation-calculator":{fields:[{label:"Area to insulate",default:"110",suffix:"m²"},{label:"Coverage per package",default:"4",suffix:"m²"},{label:"Waste",default:"10",suffix:"%"}],calc:v=>[{label:"Packages needed",value:Math.ceil(v[0]*(1+v[2]/100)/v[1])+" packages"}]},
 "excavation-calculator":{fields:[{label:"Length",default:"12",suffix:"m"},{label:"Width",default:"6",suffix:"m"},{label:"Depth",default:"1.2",suffix:"m"}],calc:v=>[{label:"Excavation volume",value:out(v[0]*v[1]*v[2])+" m³"}]},
 "paver-calculator":{fields:[{label:"Project area",default:"46",suffix:"m²"},{label:"Paver length",default:"20",suffix:"cm"},{label:"Paver width",default:"10",suffix:"cm"},{label:"Waste",default:"10",suffix:"%"}],calc:v=>{const area=v[1]*v[2]/10000,count=v[0]/area*(1+v[3]/100);return[{label:"Pavers needed",value:Math.ceil(count)+" pavers"},{label:"Includes",value:out(v[3])+"% waste"}]}},
 "pool-volume-calculator":{fields:[{label:"Pool length",default:"9",suffix:"m"},{label:"Pool width",default:"4.5",suffix:"m"},{label:"Average depth",default:"1.5",suffix:"m"}],calc:v=>[{label:"Pool volume",value:out(v[0]*v[1]*v[2])+" m³"},{label:"Liters",value:out(v[0]*v[1]*v[2]*1000)+" L"}]},
 "decking-calculator":{fields:[{label:"Deck width",default:"5",suffix:"m"},{label:"Board effective width",default:"14",suffix:"cm"},{label:"Deck length",default:"6",suffix:"m"}],calc:v=>{const boards=Math.ceil(v[0]*100/v[1]*1.1);return[{label:"Deck boards",value:boards+" boards"},{label:"Board length",value:out(v[2])+" m each"},{label:"Includes",value:"10% waste"}]}},
};

const converterSets:Record<string,{units:[string,string,number][];defaultTo:string}>={
 "length-converter":{units:[["m","Meters",1],["km","Kilometers",1000],["cm","Centimeters",.01],["ft","Feet",.3048],["in","Inches",.0254],["yd","Yards",.9144],["mi","Miles",1609.344]],defaultTo:"ft"},
 "area-converter":{units:[["sqm","Square meters",1],["sqft","Square feet",.092903],["acre","Acres",4046.8564224],["ha","Hectares",10000],["sqkm","Square kilometers",1e6]],defaultTo:"sqft"},
 "weight-converter":{units:[["kg","Kilograms",1],["g","Grams",.001],["lb","Pounds",.45359237],["oz","Ounces",.0283495],["ton","US tons",907.18474]],defaultTo:"lb"},
 "volume-converter":{units:[["l","Liters",1],["ml","Milliliters",.001],["gal","US gallons",3.785411784],["cup","US cups",.2365882365],["floz","US fluid ounces",.0295735296]],defaultTo:"gal"},
 "speed-converter":{units:[["kph","Kilometers per hour",1],["mph","Miles per hour",1.609344],["ms","Meters per second",3.6],["knot","Knots",1.852]],defaultTo:"mph"},
 "data-storage-converter":{units:[["b","Bytes",1],["kb","Kilobytes",1e3],["mb","Megabytes",1e6],["gb","Gigabytes",1e9],["tb","Terabytes",1e12]],defaultTo:"mb"},
 "pressure-converter":{units:[["pa","Pascals",1],["kpa","Kilopascals",1000],["bar","Bar",100000],["psi","PSI",6894.757293],["atm","Atmospheres",101325]],defaultTo:"psi"},
 "energy-converter":{units:[["j","Joules",1],["kj","Kilojoules",1000],["cal","Calories",4.184],["kcal","Kilocalories",4184],["wh","Watt-hours",3600],["kwh","Kilowatt-hours",3.6e6],["btu","BTU",1055.055853]],defaultTo:"kwh"},
 "power-converter":{units:[["w","Watts",1],["kw","Kilowatts",1000],["hp","Mechanical horsepower",745.699872],["btuh","BTU per hour",.29307107]],defaultTo:"hp"},
 "angle-converter":{units:[["deg","Degrees",Math.PI/180],["rad","Radians",1],["grad","Gradians",Math.PI/200],["turn","Turns",Math.PI*2]],defaultTo:"rad"},
 "force-converter":{units:[["n","Newtons",1],["kn","Kilonewtons",1000],["lbf","Pound-force",4.4482216153],["kgf","Kilogram-force",9.80665]],defaultTo:"lbf"},
 "torque-converter":{units:[["nm","Newton-meters",1],["lbft","Pound-feet",1.3558179483],["lbin","Pound-inches",.112984829]],defaultTo:"lbft"},
 "density-converter":{units:[["kgm3","Kilograms per cubic meter",1],["gcm3","Grams per cubic centimeter",1000],["lbft3","Pounds per cubic foot",16.018463],["lbin3","Pounds per cubic inch",27679.9047]],defaultTo:"lbft3"},
 "time-converter":{units:[["sec","Seconds",1],["min","Minutes",60],["hr","Hours",3600],["day","Days",86400],["week","Weeks",604800]],defaultTo:"hr"},
 "frequency-converter":{units:[["hz","Hertz",1],["khz","Kilohertz",1e3],["mhz","Megahertz",1e6],["ghz","Gigahertz",1e9]],defaultTo:"mhz"},
 "acceleration-converter":{units:[["ms2","Meters per second²",1],["fts2","Feet per second²",.3048],["g","Standard gravity",9.80665]],defaultTo:"g"},
 "flow-rate-converter":{units:[["lmin","Liters per minute",1],["gpm","US gallons per minute",3.785411784],["m3h","Cubic meters per hour",16.6666667]],defaultTo:"gpm"},
 "cooking-measurement-converter":{units:[["ml","Milliliters",1],["l","Liters",1000],["tsp","US teaspoons",4.92892159],["tbsp","US tablespoons",14.7867648],["cup","US cups",236.5882365],["floz","US fluid ounces",29.5735296]],defaultTo:"cup"},
 "typography-unit-converter":{units:[["px","Pixels",1],["pt","Points",96/72],["pc","Picas",16],["rem","rem at 16px root",16]],defaultTo:"rem"},
 "data-rate-converter":{units:[["bps","Bits per second",1],["kbps","Kilobits per second",1e3],["mbps","Megabits per second",1e6],["gbps","Gigabits per second",1e9],["kBps","Kilobytes per second",8e3],["MBps","Megabytes per second",8e6],["GBps","Gigabytes per second",8e9]],defaultTo:"MBps"},
};

const Result=({items}:{items:Item[]})=><div className="engine-results">{items.map(x=><div key={x.label}><span>{x.label}</span><strong>{x.value}</strong></div>)}</div>;

export default function CalculatorEngine({slug}:{slug:string}){
 const [unitSystem,setUnitSystem]=useState<"us"|"metric">("us");
 const preset=unitSystem==="metric"&&metricPresets[slug]?metricPresets[slug]:presets[slug]; const defaults=presets[slug]?.fields.map(f=>f.default)||[];
 const [values,setValues]=useState<string[]>(defaults); const [from,setFrom]=useState(""); const [to,setTo]=useState("");
 const initialText=slug==="json-formatter"||slug==="json-to-csv-converter"?'{\n  "name": "Amarildo Tools",\n  "tools": 300\n}':slug==="csv-to-json-converter"?"name,category\nPercentage Calculator,Math\nConcrete Calculator,Construction":slug==="url-parser"||slug==="query-string-parser"?"https://amarildotools.com/tools?category=math&free=true#results":slug==="hex-rgb-converter"?"#1463ff":slug==="number-base-converter"?"255":slug==="email-list-cleaner"?"Hello@example.com, hello@example.com, team@amarildotools.com":slug==="number-list-cleaner"?"12, 7, 12, 42, 3.5, 7":["average-calculator","median-calculator","mode-calculator","standard-deviation-calculator","geometric-mean-calculator","harmonic-mean-calculator","variance-calculator","range-calculator","sum-calculator"].includes(slug)?"12, 18, 18, 21, 26, 31":"Amarildo Tools makes useful online tools clear and fast.";
 const [text,setText]=useState(initialText);
 const [message,setMessage]=useState("Ready");
 const results=useMemo(()=>preset?preset.calc(values.map(n)):[],[preset,values]);
 const update=(i:number,value:string)=>setValues(old=>old.map((x,index)=>index===i?value:x));
 if(slug==="basic-calculator")return <BasicCalculator/>;
 if(preset)return <div className="engine">{metricPresets[slug]&&<div className="unit-system"><span>Measurement system</span><div><button className={unitSystem==="us"?"active":""} onClick={()=>{setUnitSystem("us");setValues(presets[slug].fields.map(f=>f.default))}}>US / Imperial</button><button className={unitSystem==="metric"?"active":""} onClick={()=>{setUnitSystem("metric");setValues(metricPresets[slug].fields.map(f=>f.default))}}>Metric</button></div></div>}<div className="engine-grid">{preset.fields.map((f,i)=><label className="engine-field" key={f.label}><span>{f.label}</span><div><input inputMode="decimal" value={values[i]??f.default} onChange={e=>update(i,e.target.value)}/>{f.suffix&&<i>{f.suffix}</i>}</div></label>)}</div><Result items={results}/>{slug==="bmi-calculator"&&<p className="health-note">BMI is a general screening tool and is not medical advice.</p>}</div>;
 if(slug==="age-calculator"){const dateText=text.match(/^\d{4}-/)?text:"1990-01-01",birth=new Date(dateText+"T00:00:00"),today=new Date();let result="Enter a valid past date";if(!isNaN(birth.getTime())&&birth<=today){let y=today.getFullYear()-birth.getFullYear(),m=today.getMonth()-birth.getMonth(),d=today.getDate()-birth.getDate();if(d<0){m--;d+=new Date(today.getFullYear(),today.getMonth(),0).getDate()}if(m<0){y--;m+=12}result=y+" years, "+m+" months, "+d+" days"}return <div className="engine"><label className="engine-field"><span>Date of birth</span><div><input type="date" value={dateText} onChange={e=>setText(e.target.value)}/></div></label><Result items={[{label:"Exact age",value:result}]}/></div>}
 const set=converterSets[slug];
 if(set){const source=from||set.units[0][0],target=to||set.defaultTo,sv=set.units.find(x=>x[0]===source)?.[2]||1,tv=set.units.find(x=>x[0]===target)?.[2]||1;return <div className="engine"><div className="engine-grid"><label className="engine-field"><span>Value</span><div><input inputMode="decimal" value={text.match(/^-?\d/) ? text : "1"} onChange={e=>setText(e.target.value)}/></div></label><label className="engine-field"><span>From</span><select value={source} onChange={e=>setFrom(e.target.value)}>{set.units.map(u=><option key={u[0]} value={u[0]}>{u[1]}</option>)}</select></label><label className="engine-field"><span>To</span><select value={target} onChange={e=>setTo(e.target.value)}>{set.units.map(u=><option key={u[0]} value={u[0]}>{u[1]}</option>)}</select></label></div><Result items={[{label:"Converted value",value:out(n(text||"1")*sv/tv,6)+" "+target}]}/></div>}
 if(slug==="temperature-converter"){const source=from||"c",target=to||"f",value=n(text),cel=source==="c"?value:source==="f"?(value-32)*5/9:value-273.15,converted=target==="c"?cel:target==="f"?cel*9/5+32:cel+273.15,units=[["c","Celsius"],["f","Fahrenheit"],["k","Kelvin"]];return <div className="engine"><div className="engine-grid"><label className="engine-field"><span>Value</span><div><input value={text.match(/^-?\d/) ? text : "0"} onChange={e=>setText(e.target.value)}/></div></label>{[["From",source,setFrom],["To",target,setTo]].map(([label,val,setter])=><label className="engine-field" key={label as string}><span>{label as string}</span><select value={val as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}>{units.map(u=><option key={u[0]} value={u[0]}>{u[1]}</option>)}</select></label>)}</div><Result items={[{label:"Converted temperature",value:out(converted,4)+"° "+target.toUpperCase()}]}/></div>}
 if(slug==="fuel-economy-converter"){const source=from||"mpg-us",target=to||"l100km",value=n(text.match(/^-?\d/)?text:"30"),toL100=(x:number,u:string)=>u==="mpg-us"?235.214583/x:u==="mpg-uk"?282.480936/x:u==="kml"?100/x:x,base=toL100(value,source),converted=target==="mpg-us"?235.214583/base:target==="mpg-uk"?282.480936/base:target==="kml"?100/base:base,units=[["mpg-us","MPG (US)"],["mpg-uk","MPG (UK)"],["kml","Kilometers per liter"],["l100km","Liters per 100 km"]];return <div className="engine"><div className="engine-grid"><label className="engine-field"><span>Value</span><div><input value={text.match(/^-?\d/)?text:"30"} onChange={e=>setText(e.target.value)}/></div></label>{[["From",source,setFrom],["To",target,setTo]].map(([label,val,setter])=><label className="engine-field" key={label as string}><span>{label as string}</span><select value={val as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}>{units.map(u=><option key={u[0]} value={u[0]}>{u[1]}</option>)}</select></label>)}</div><Result items={[{label:"Converted fuel economy",value:out(converted,6)+" "+target}]}/></div>}
 if(slug==="average-calculator"){const vals=text.split(/[\s,]+/).map(Number).filter(Number.isFinite),avg=vals.reduce((s,x)=>s+x,0)/vals.length;return <TextTool text={text} setText={setText} label="Numbers separated by commas" items={[{label:"Average",value:out(avg)},{label:"Count",value:String(vals.length)},{label:"Sum",value:out(vals.reduce((s,x)=>s+x,0))}]}/>}
 if(["median-calculator","mode-calculator","standard-deviation-calculator"].includes(slug)){const vals=text.split(/[\s,]+/).map(Number).filter(Number.isFinite).sort((x,y)=>x-y);let items:Item[]=[];if(slug==="median-calculator"){const mid=Math.floor(vals.length/2),median=vals.length%2?vals[mid]:(vals[mid-1]+vals[mid])/2;items=[{label:"Median",value:out(median)},{label:"Values",value:String(vals.length)}]}else if(slug==="mode-calculator"){const counts=new Map<number,number>();vals.forEach(x=>counts.set(x,(counts.get(x)||0)+1));const max=Math.max(0,...counts.values()),modes=[...counts].filter(x=>x[1]===max&&max>1).map(x=>x[0]);items=[{label:"Mode",value:modes.length?modes.join(", "):"No repeated mode"},{label:"Highest frequency",value:String(max)}]}else{const mean=vals.reduce((s,x)=>s+x,0)/vals.length,pop=Math.sqrt(vals.reduce((s,x)=>s+(x-mean)**2,0)/vals.length),sample=Math.sqrt(vals.reduce((s,x)=>s+(x-mean)**2,0)/(vals.length-1));items=[{label:"Population deviation",value:out(pop,6)},{label:"Sample deviation",value:out(sample,6)},{label:"Mean",value:out(mean)}]}return <TextTool text={text} setText={setText} label="Numbers separated by commas" items={items}/>}
 if(["geometric-mean-calculator","harmonic-mean-calculator","variance-calculator","range-calculator","sum-calculator"].includes(slug)){const vals=text.split(/[\s,]+/).map(Number).filter(Number.isFinite),sum=vals.reduce((s,x)=>s+x,0),mean=sum/vals.length;let items:Item[]=[];if(slug==="geometric-mean-calculator")items=[{label:"Geometric mean",value:vals.some(x=>x<=0)?"Use positive values":out(Math.exp(vals.reduce((s,x)=>s+Math.log(x),0)/vals.length),8)}];else if(slug==="harmonic-mean-calculator")items=[{label:"Harmonic mean",value:vals.some(x=>x===0)?"Values cannot include zero":out(vals.length/vals.reduce((s,x)=>s+1/x,0),8)}];else if(slug==="variance-calculator"){const pop=vals.reduce((s,x)=>s+(x-mean)**2,0)/vals.length,sample=vals.reduce((s,x)=>s+(x-mean)**2,0)/(vals.length-1);items=[{label:"Population variance",value:out(pop,8)},{label:"Sample variance",value:out(sample,8)}]}else if(slug==="range-calculator")items=[{label:"Range",value:out(Math.max(...vals)-Math.min(...vals))},{label:"Minimum",value:out(Math.min(...vals))},{label:"Maximum",value:out(Math.max(...vals))}];else items=[{label:"Sum",value:out(sum)},{label:"Count",value:String(vals.length)}];return <TextTool text={text} setText={setText} label="Numbers separated by commas" items={items}/>}
 if(slug==="word-counter"){const trimmed=text.trim(),words=trimmed?trimmed.split(/\s+/).length:0,sentences=trimmed?(trimmed.match(/[.!?]+/g)||[]).length:0;return <TextTool text={text} setText={setText} label="Enter or paste text" items={[{label:"Words",value:String(words)},{label:"Characters",value:String(text.length)},{label:"Sentences",value:String(sentences)},{label:"Reading time",value:Math.max(1,Math.ceil(words/200))+" min"}]}/>}
 if(slug==="meta-title-checker"||slug==="meta-description-checker"){const target=slug==="meta-title-checker"?60:155,len=text.length,status=len===0?"Start typing":len<=target?"Within the practical limit":"Consider shortening";return <TextTool text={text} setText={setText} label={slug==="meta-title-checker"?"Proposed meta title":"Proposed meta description"} items={[{label:"Characters",value:String(len)},{label:"Suggested maximum",value:String(target)},{label:"Status",value:status}]}/>}
 if(slug==="keyword-density-checker"){const keyword=from.trim().toLowerCase(),words=(text.toLowerCase().match(/\b[\p{L}\p{N}'-]+\b/gu)||[]),matches=keyword?text.toLowerCase().split(keyword).length-1:0;return <div className="engine"><label className="engine-field"><span>Keyword or phrase</span><div><input value={from} onChange={e=>setFrom(e.target.value)} placeholder="calculator"/></div></label><label className="engine-field utility-text"><span>Text to check</span><textarea className="json-editor" value={text} onChange={e=>setText(e.target.value)}/></label><Result items={[{label:"Occurrences",value:String(matches)},{label:"Total words",value:String(words.length)},{label:"Density",value:keyword&&words.length?out(matches/words.length*100,3)+"%":"0%"}]}/></div>}
 if(slug==="word-frequency-counter"){const words=(text.toLowerCase().match(/\b[\p{L}\p{N}'-]+\b/gu)||[]),counts=new Map<string,number>();words.forEach(w=>counts.set(w,(counts.get(w)||0)+1));const top=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>x[0]+" ("+x[1]+")").join(", ");return <TextTool text={text} setText={setText} label="Text to analyze" items={[{label:"Unique words",value:String(counts.size)},{label:"Most frequent words",value:top||"—"}]}/>}
 if(slug==="url-parser"){let items:Item[];try{const u=new URL(text);items=[{label:"Protocol",value:u.protocol},{label:"Host",value:u.host},{label:"Path",value:u.pathname||"/"},{label:"Query",value:u.search||"None"},{label:"Fragment",value:u.hash||"None"}]}catch{items=[{label:"Result",value:"Enter a complete valid URL"}]}return <TextTool text={text} setText={setText} label="URL" items={items}/>}
 if(slug==="query-string-parser"){let value="";try{const u=new URL(text),pairs=[...u.searchParams.entries()];value=pairs.length?pairs.map(x=>x[0]+" = "+x[1]).join(" • "):"No query parameters"}catch{value="Enter a complete valid URL"}return <TextTool text={text} setText={setText} label="URL with query parameters" items={[{label:"Parameters",value}]}/>}
 if(slug==="number-base-converter"){const source=from||"10",target=to||"16",base=parseInt(text,Number(source)),result=Number.isFinite(base)?base.toString(Number(target)).toUpperCase():"Invalid number",bases=[["2","Binary"],["8","Octal"],["10","Decimal"],["16","Hexadecimal"]];return <div className="engine"><div className="engine-grid"><label className="engine-field"><span>Number</span><div><input value={text} onChange={e=>setText(e.target.value)}/></div></label>{[["From base",source,setFrom],["To base",target,setTo]].map(([label,val,setter])=><label className="engine-field" key={label as string}><span>{label as string}</span><select value={val as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}>{bases.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>)}</div><Result items={[{label:"Converted value",value:result}]}/></div>}
 if(slug==="hex-rgb-converter"){const clean=text.trim().replace("#","");let value="Enter a 3- or 6-digit HEX color";if(/^[0-9a-f]{3}$/i.test(clean)||/^[0-9a-f]{6}$/i.test(clean)){const h=clean.length===3?clean.split("").map(x=>x+x).join(""):clean,num=parseInt(h,16);value="rgb("+((num>>16)&255)+", "+((num>>8)&255)+", "+(num&255)+")"}return <TextTool text={text} setText={setText} label="HEX color" items={[{label:"RGB color",value}]}/>}
 if(slug==="regex-tester"){let matches:string[]=[];let error="";try{matches=text.match(new RegExp(from||"tool","gi"))||[]}catch(e){error=e instanceof Error?e.message:"Invalid expression"}return <div className="engine"><label className="engine-field"><span>Regular expression</span><div><input value={from} onChange={e=>setFrom(e.target.value)} placeholder="tool"/></div></label><label className="engine-field utility-text"><span>Test text</span><textarea className="json-editor" value={text} onChange={e=>setText(e.target.value)}/></label><Result items={[{label:"Matches",value:error||String(matches.length)},{label:"Matched text",value:matches.slice(0,10).join(", ")||"None"}]}/></div>}
 if(slug==="uuid-generator"||slug==="password-generator"){const generate=()=>{if(slug==="uuid-generator")setMessage(crypto.randomUUID());else{const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*",bytes=crypto.getRandomValues(new Uint32Array(20));setMessage([...bytes].map(x=>chars[x%chars.length]).join(""))}};return <div className="engine generator-tool"><button onClick={generate}>{slug==="uuid-generator"?"Generate UUID":"Generate password"}</button><Result items={[{label:"Generated value",value:message==="Ready"?"Select generate":message}]}/></div>}
 if(slug==="slug-generator"){const run=()=>setText(text.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""));return <UtilityEditor text={text} setText={setText} actions={[["Generate slug",run]]}/>}
 if(slug==="case-converter"){return <UtilityEditor text={text} setText={setText} actions={[["UPPERCASE",()=>setText(text.toUpperCase())],["lowercase",()=>setText(text.toLowerCase())],["Title Case",()=>setText(text.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()))],["Sentence case",()=>setText(text.toLowerCase().replace(/(^\s*\w|[.!?]\s+\w)/g,c=>c.toUpperCase()))]]}/>}
 if(slug==="sort-lines-tool"){return <UtilityEditor text={text} setText={setText} actions={[["Sort A–Z",()=>setText(text.split(/\r?\n/).filter(Boolean).sort((a,b)=>a.localeCompare(b)).join("\n"))],["Sort Z–A",()=>setText(text.split(/\r?\n/).filter(Boolean).sort((a,b)=>b.localeCompare(a)).join("\n"))]]}/>}
 if(slug==="remove-duplicate-lines"){return <UtilityEditor text={text} setText={setText} actions={[["Remove duplicates",()=>setText([...new Set(text.split(/\r?\n/))].join("\n"))]]}/>}
 if(slug==="whitespace-cleaner"){return <UtilityEditor text={text} setText={setText} actions={[["Clean whitespace",()=>setText(text.split(/\r?\n/).map(x=>x.trim().replace(/\s+/g," ")).filter((x,i,a)=>x||a[i-1]).join("\n"))]]}/>}
 if(slug==="reverse-text-tool"){return <UtilityEditor text={text} setText={setText} actions={[["Reverse characters",()=>setText([...text].reverse().join(""))],["Reverse lines",()=>setText(text.split(/\r?\n/).reverse().join("\n"))]]}/>}
 if(slug==="css-minifier"){return <UtilityEditor text={text} setText={setText} actions={[["Minify CSS",()=>setText(text.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\s+/g," ").replace(/\s*([{}:;,])\s*/g,"$1").trim())]]}/>}
 if(slug==="javascript-string-escaper"){return <UtilityEditor text={text} setText={setText} actions={[["Escape",()=>setText(JSON.stringify(text).slice(1,-1))],["Unescape",()=>{try{setText(JSON.parse('"'+text.replace(/"/g,'\\"')+'"'))}catch{setMessage("Could not unescape")}}]]}/>}
 if(slug==="html-entity-encoder"){const encode=()=>setText(text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")),decode=()=>{const el=document.createElement("textarea");el.innerHTML=text;setText(el.value)};return <UtilityEditor text={text} setText={setText} actions={[["Encode entities",encode],["Decode entities",decode]]}/>}
 if(slug==="json-to-csv-converter"){const run=()=>{try{const parsed=JSON.parse(text),rows=Array.isArray(parsed)?parsed:[parsed],headers=[...new Set(rows.flatMap((r:Record<string,unknown>)=>Object.keys(r)))],csv=[headers.join(","),...rows.map((r:Record<string,unknown>)=>headers.map(h=>JSON.stringify(r[h]??"")).join(","))].join("\n");setText(csv)}catch{setMessage("Enter valid JSON")}};return <UtilityEditor text={text} setText={setText} actions={[["Convert to CSV",run]]}/>}
 if(slug==="csv-to-json-converter"){const run=()=>{const rows=text.trim().split(/\r?\n/).map(r=>r.split(",")),headers=rows.shift()||[],data=rows.map(row=>Object.fromEntries(headers.map((h,i)=>[h.trim(),(row[i]||"").trim()])));setText(JSON.stringify(data,null,2))};return <UtilityEditor text={text} setText={setText} actions={[["Convert to JSON",run]]}/>}
 if(slug==="email-list-cleaner"){const run=()=>{const emails=text.toLowerCase().match(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/g)||[];setText([...new Set(emails)].sort().join("\n"))};return <UtilityEditor text={text} setText={setText} actions={[["Clean email list",run]]}/>}
 if(slug==="number-list-cleaner"){const run=()=>{const nums=(text.match(/-?\d*\.?\d+/g)||[]).map(Number);setText([...new Set(nums)].sort((a,b)=>a-b).join("\n"))};return <UtilityEditor text={text} setText={setText} actions={[["Clean number list",run]]}/>}
 if(slug==="lorem-ipsum-generator"){const lorem="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";return <div className="engine generator-tool"><button onClick={()=>setText(Array(3).fill(lorem).join("\n\n"))}>Generate 3 paragraphs</button><textarea className="json-editor" value={text} onChange={e=>setText(e.target.value)}/></div>}
 if(slug==="unix-timestamp-converter"){const stamp=n(text)||Math.floor(Date.now()/1000),date=new Date(stamp*(stamp>1e12?1:1000));return <TextTool text={text.match(/^\d/) ? text : String(Math.floor(Date.now()/1000))} setText={setText} label="Unix timestamp" items={[{label:"UTC date",value:isNaN(date.getTime())?"Invalid timestamp":date.toUTCString()}]}/>}
 if(slug==="base64-encoder-decoder"||slug==="url-encoder-decoder"){const base64=slug.startsWith("base64");const run=(decode:boolean)=>{try{setText(base64?(decode?decodeURIComponent(escape(atob(text))):btoa(unescape(encodeURIComponent(text)))):(decode?decodeURIComponent(text):encodeURIComponent(text)));setMessage(decode?"Decoded":"Encoded")}catch{setMessage("Input could not be decoded")}};return <div className="engine"><textarea className="json-editor" value={text} onChange={e=>setText(e.target.value)}/><div className="json-actions"><button onClick={()=>run(false)}>Encode</button><button className="secondary" onClick={()=>run(true)}>Decode</button><span>{message}</span></div></div>}
 if(slug==="json-formatter"){const run=(min:boolean)=>{try{setText(JSON.stringify(JSON.parse(text),null,min?0:2));setMessage("Valid JSON")}catch(e){setMessage(e instanceof Error?e.message:"Invalid JSON")}};return <div className="engine"><textarea className="json-editor" value={text} onChange={e=>setText(e.target.value)}/><div className="json-actions"><button onClick={()=>run(false)}>Format JSON</button><button className="secondary" onClick={()=>run(true)}>Minify</button><span className={message==="Valid JSON"?"valid":"invalid"}>{message}</span></div></div>}
 return <div className="engine"><p>This tool is being prepared.</p></div>;
}

function BasicCalculator(){
 const [display,setDisplay]=useState("0"),[stored,setStored]=useState<number|null>(null),[operator,setOperator]=useState<"+"|"−"|"×"|"÷"|null>(null),[fresh,setFresh]=useState(true);
 const calculate=(a:number,b:number,op:string|null)=>op==="+"?a+b:op==="−"?a-b:op==="×"?a*b:op==="÷"?(b===0?NaN:a/b):b;
 const digit=(value:string)=>{setDisplay(old=>fresh||old==="0"?value:old+value);setFresh(false)};
 const choose=(op:"+"|"−"|"×"|"÷")=>{const current=n(display);if(stored!==null&&operator&&!fresh){const result=calculate(stored,current,operator);setDisplay(Number.isFinite(result)?String(result):"Cannot divide by zero");setStored(result)}else setStored(current);setOperator(op);setFresh(true)};
 const equals=()=>{if(stored===null||!operator)return;const result=calculate(stored,n(display),operator);setDisplay(Number.isFinite(result)?String(result):"Cannot divide by zero");setStored(null);setOperator(null);setFresh(true)};
 const clear=()=>{setDisplay("0");setStored(null);setOperator(null);setFresh(true)};
 return <div className="engine basic-calculator"><div className="basic-display"><span>{stored!==null&&operator?out(stored,10)+" "+operator:"Ready"}</span><strong>{display}</strong></div><div className="basic-keypad"><button className="clear" onClick={clear}>AC</button><button onClick={()=>setDisplay(old=>String(-n(old)))}>±</button><button onClick={()=>setDisplay(old=>String(n(old)/100))}>%</button><button className="operation" onClick={()=>choose("÷")}>÷</button>{["7","8","9"].map(x=><button key={x} onClick={()=>digit(x)}>{x}</button>)}<button className="operation" onClick={()=>choose("×")}>×</button>{["4","5","6"].map(x=><button key={x} onClick={()=>digit(x)}>{x}</button>)}<button className="operation" onClick={()=>choose("−")}>−</button>{["1","2","3"].map(x=><button key={x} onClick={()=>digit(x)}>{x}</button>)}<button className="operation" onClick={()=>choose("+")}>+</button><button className="zero" onClick={()=>digit("0")}>0</button><button onClick={()=>!display.includes(".")&&digit(".")}>.</button><button className="equals" onClick={equals}>=</button></div></div>
}

function TextTool({text,setText,label,items}:{text:string,setText:(v:string)=>void,label:string,items:Item[]}){return <div className="engine"><label className="engine-field"><span>{label}</span><textarea className="json-editor" value={text} onChange={e=>setText(e.target.value)}/></label><Result items={items}/></div>}
function UtilityEditor({text,setText,actions}:{text:string,setText:(v:string)=>void,actions:[string,()=>void][]}){return <div className="engine"><textarea className="json-editor" value={text} onChange={e=>setText(e.target.value)} aria-label="Tool input and output"/><div className="json-actions">{actions.map(([label,action])=><button key={label} onClick={action}>{label}</button>)}</div></div>}
