export type ToolDefinition = {
  slug: string; name: string; short: string; category: string; description: string;
  formula: string; guide: string[]; faq: { q: string; a: string }[];
};

const coreTools: ToolDefinition[] = [
  { slug:"percentage-calculator", name:"Percentage Calculator", short:"Find percentages, increases, decreases, and differences.", category:"Everyday", description:"Calculate any percentage of a number instantly. See the formula and a clear result without signing up.", formula:"Percentage result = (percentage ÷ 100) × number", guide:["Enter the percentage you want to calculate.","Enter the number the percentage applies to.","Read the result, which updates as you type."], faq:[{q:"How do I find 20% of a number?",a:"Multiply the number by 0.20. For example, 20% of 150 is 30."},{q:"Can this calculator use decimals?",a:"Yes. Both the percentage and the number can include decimals."}] },
  { slug:"loan-payment-calculator", name:"Loan Payment Calculator", short:"Estimate monthly payments, interest, and total cost.", category:"Finance", description:"Estimate a fixed loan payment using the amount borrowed, annual interest rate, and repayment term.", formula:"Payment = P × [r(1+r)ⁿ] ÷ [(1+r)ⁿ−1]", guide:["Enter the principal amount you plan to borrow.","Add the annual interest rate and loan term.","Compare the monthly payment, total interest, and total repayment."], faq:[{q:"Does this include fees?",a:"No. The estimate uses principal and interest only unless fees are included in the loan amount."},{q:"What interest rate should I enter?",a:"Use the annual percentage rate stated by your lender, excluding separate fees."}] },
  { slug:"compound-interest-calculator", name:"Compound Interest Calculator", short:"Project savings growth with regular contributions.", category:"Finance", description:"Project how an initial balance and monthly contributions may grow with compound interest.", formula:"Future value combines compounded principal and recurring contributions", guide:["Enter your starting balance and monthly contribution.","Choose an annual return and time period.","Review the estimated ending balance and total growth."], faq:[{q:"Are returns guaranteed?",a:"No. This is a mathematical projection, not a guarantee of investment performance."},{q:"How often is interest compounded?",a:"This calculator compounds monthly."}] },
  { slug:"profit-margin-calculator", name:"Profit Margin Calculator", short:"Calculate margin, markup, revenue, and profit.", category:"Business", description:"Calculate gross profit, profit margin, and markup from cost and selling price.", formula:"Margin = (selling price − cost) ÷ selling price × 100", guide:["Enter the cost of the product or service.","Enter its selling price.","Review gross profit, margin, and markup."], faq:[{q:"What is the difference between margin and markup?",a:"Margin compares profit with selling price. Markup compares profit with cost."},{q:"Can margin exceed 100%?",a:"Gross margin normally cannot exceed 100%, but markup can."}] },
  { slug:"bmi-calculator", name:"BMI Calculator", short:"Estimate body mass index from height and weight.", category:"Health", description:"Estimate adult body mass index using metric height and weight measurements.", formula:"BMI = weight in kilograms ÷ height in meters²", guide:["Enter an adult height in centimeters.","Enter weight in kilograms.","View the estimated BMI and standard screening category."], faq:[{q:"Is BMI a diagnosis?",a:"No. BMI is a screening measurement and does not diagnose health conditions."},{q:"Is this suitable for children?",a:"No. Children and teens require age- and sex-specific BMI interpretation."}] },
  { slug:"age-calculator", name:"Age Calculator", short:"Calculate exact age from a date of birth.", category:"Everyday", description:"Calculate age in years, months, and days from a date of birth to today.", formula:"Age = today’s date − date of birth", guide:["Enter the date of birth.","The calculator compares it with today’s date.","See the completed years, months, and days."], faq:[{q:"Does the calculator account for leap years?",a:"Yes. It uses calendar dates and accounts for varying month lengths and leap years."},{q:"Can I enter a future date?",a:"No. A date of birth must be today or earlier."}] },
  { slug:"length-converter", name:"Length Converter", short:"Convert meters, feet, inches, miles, and more.", category:"Converters", description:"Convert common metric and imperial length units with immediate, precise results.", formula:"Converted value = input value × source factor ÷ target factor", guide:["Enter a length value.","Choose the source and target units.","Copy or read the converted result."], faq:[{q:"Which units are supported?",a:"Meters, kilometers, centimeters, feet, inches, yards, and miles are supported."},{q:"How precise are the results?",a:"Results show up to six decimal places where useful."}] },
  { slug:"temperature-converter", name:"Temperature Converter", short:"Convert Celsius, Fahrenheit, and Kelvin.", category:"Converters", description:"Convert temperatures between Celsius, Fahrenheit, and Kelvin instantly.", formula:"°F = (°C × 9/5) + 32", guide:["Enter a temperature.","Choose the starting and target scales.","Read the converted temperature."], faq:[{q:"What is absolute zero?",a:"Absolute zero is 0 Kelvin, equal to −273.15°C or −459.67°F."},{q:"Can Kelvin be negative?",a:"No physical temperature is below 0 Kelvin."}] },
  { slug:"concrete-calculator", name:"Concrete Calculator", short:"Estimate concrete volume for rectangular slabs.", category:"Construction", description:"Estimate the cubic yards of concrete required for a rectangular slab and include a practical waste allowance.", formula:"Volume = length × width × thickness", guide:["Enter slab length and width in feet.","Enter thickness in inches.","Review base cubic yards and the estimate with 10% waste."], faq:[{q:"Why add a waste allowance?",a:"Extra material helps cover uneven excavation, spillage, and measurement variation."},{q:"Should I round up when ordering?",a:"Suppliers commonly sell concrete in set increments, so confirm the order quantity with the supplier."}] },
  { slug:"json-formatter", name:"JSON Formatter", short:"Format, validate, and minify JSON locally.", category:"Developer", description:"Validate, format, or minify JSON directly in your browser. Your data is not uploaded.", formula:"Valid JSON follows the JavaScript Object Notation grammar", guide:["Paste JSON into the editor.","Choose Format or Minify.","Fix any validation message shown below the editor."], faq:[{q:"Is my JSON uploaded?",a:"No. Processing happens locally in your browser."},{q:"What indentation does Format use?",a:"Formatted output uses two spaces per indentation level."}] },
];

const make=(slug:string,name:string,short:string,category:string,formula:string):ToolDefinition=>({
 slug,name,short,category,formula,
 description:short+" Use this free browser-based "+name.toLowerCase()+" for an immediate result with a clear method.",
 guide:["Enter the known values in the labeled fields.","Review or adjust the inputs as needed.","Use the calculated result for planning and comparison."],
 faq:[{q:"Is this tool free?",a:"Yes. It is free to use and does not require an account."},{q:"Are the results exact?",a:"The math follows the displayed formula. Real-world costs, rates, measurements, and rounding can vary."}]
});

const expandedTools: ToolDefinition[] = [
 make("mortgage-payment-calculator","Mortgage Payment Calculator","Estimate principal and interest for a fixed-rate mortgage.","Finance","Monthly payment uses principal, monthly rate, and number of payments"),
 make("simple-interest-calculator","Simple Interest Calculator","Calculate interest without compounding.","Finance","Interest = principal × annual rate × time"),
 make("savings-goal-calculator","Savings Goal Calculator","Find the monthly amount needed to reach a savings target.","Finance","Monthly saving = (goal − current savings) ÷ months"),
 make("debt-to-income-calculator","Debt-to-Income Calculator","Compare monthly debt payments with gross monthly income.","Finance","DTI = monthly debt ÷ gross monthly income × 100"),
 make("credit-card-payoff-calculator","Credit Card Payoff Calculator","Estimate how long fixed payments may take to clear a balance.","Finance","Balance is reduced monthly after interest and payment"),
 make("discount-calculator","Discount Calculator","Find sale price and total savings from a discount.","Everyday","Sale price = original price × (1 − discount rate)"),
 make("tip-calculator","Tip Calculator","Calculate a tip and split the total bill.","Everyday","Total = bill + (bill × tip rate)"),
 make("average-calculator","Average Calculator","Find the arithmetic mean of a list of numbers.","Everyday","Average = sum of values ÷ number of values"),
 make("ratio-calculator","Ratio Calculator","Simplify a two-number ratio to lowest terms.","Everyday","Simplified ratio divides both values by their greatest common divisor"),
 make("fraction-to-percentage-calculator","Fraction to Percentage Calculator","Convert a numerator and denominator into a percentage.","Everyday","Percentage = numerator ÷ denominator × 100"),
 make("square-footage-calculator","Square Footage Calculator","Calculate rectangular floor or wall area.","Construction","Area = length × width"),
 make("paint-calculator","Paint Calculator","Estimate paint gallons for walls and coats.","Construction","Gallons = wall area × coats ÷ coverage"),
 make("flooring-calculator","Flooring Calculator","Estimate flooring area including a waste allowance.","Construction","Order area = length × width × (1 + waste rate)"),
 make("roofing-calculator","Roofing Calculator","Estimate roof area and roofing squares for a gable roof.","Construction","Roof area = footprint area × pitch factor"),
 make("gravel-calculator","Gravel Calculator","Estimate cubic yards of gravel for a rectangular area.","Construction","Cubic yards = length × width × depth ÷ 27"),
 make("drywall-calculator","Drywall Calculator","Estimate drywall sheets from wall area.","Construction","Sheets = wall area ÷ sheet area, rounded up"),
 make("roas-calculator","ROAS Calculator","Measure advertising revenue returned per dollar spent.","Business","ROAS = revenue from ads ÷ ad spend"),
 make("cpc-calculator","Cost Per Click Calculator","Calculate average advertising cost per click.","Business","CPC = advertising cost ÷ clicks"),
 make("cpm-calculator","CPM Calculator","Calculate advertising cost per thousand impressions.","Business","CPM = advertising cost ÷ impressions × 1,000"),
 make("ctr-calculator","Click-Through Rate Calculator","Calculate clicks as a percentage of impressions.","Business","CTR = clicks ÷ impressions × 100"),
 make("conversion-rate-calculator","Conversion Rate Calculator","Calculate conversions as a percentage of visitors or clicks.","Business","Conversion rate = conversions ÷ total interactions × 100"),
 make("break-even-calculator","Break-Even Calculator","Find the number of units needed to cover fixed costs.","Business","Break-even units = fixed costs ÷ (price − variable cost)"),
 make("sales-tax-calculator","Sales Tax Calculator","Add a tax rate to a purchase amount.","Business","Total = price + (price × tax rate)"),
 make("area-converter","Area Converter","Convert square meters, square feet, acres, and hectares.","Converters","Converted area = input × source factor ÷ target factor"),
 make("weight-converter","Weight Converter","Convert kilograms, pounds, ounces, grams, and tons.","Converters","Converted weight = input × source factor ÷ target factor"),
 make("volume-converter","Volume Converter","Convert liters, gallons, cups, milliliters, and fluid ounces.","Converters","Converted volume = input × source factor ÷ target factor"),
 make("speed-converter","Speed Converter","Convert mph, km/h, meters per second, and knots.","Converters","Converted speed = input × source factor ÷ target factor"),
 make("data-storage-converter","Data Storage Converter","Convert bytes, kilobytes, megabytes, gigabytes, and terabytes.","Converters","Converted storage = input × source factor ÷ target factor"),
 make("base64-encoder-decoder","Base64 Encoder and Decoder","Encode plain text to Base64 or decode Base64 locally.","Developer","Base64 represents binary data using 64 text characters"),
 make("url-encoder-decoder","URL Encoder and Decoder","Encode or decode text for safe use in URLs.","Developer","URL encoding replaces reserved characters with percent-encoded bytes"),
 make("word-counter","Word and Character Counter","Count words, characters, sentences, and reading time.","Developer","Counts are derived directly from the entered text"),
 make("unix-timestamp-converter","Unix Timestamp Converter","Convert Unix timestamps into readable UTC dates.","Developer","Unix time counts seconds since January 1, 1970 UTC"),
];

const calculatorBatchTwo: ToolDefinition[] = [
 make("percentage-increase-calculator","Percentage Increase Calculator","Measure the percentage increase from an old value to a new value.","Everyday","Increase % = (new value − old value) ÷ old value × 100"),
 make("percentage-decrease-calculator","Percentage Decrease Calculator","Measure the percentage decrease from an old value to a new value.","Everyday","Decrease % = (old value − new value) ÷ old value × 100"),
 make("percentage-difference-calculator","Percentage Difference Calculator","Compare two values using their average as the reference.","Everyday","Difference % = |A − B| ÷ ((A + B) ÷ 2) × 100"),
 make("grade-percentage-calculator","Grade Percentage Calculator","Calculate a test percentage from points earned and available.","Everyday","Grade = points earned ÷ total points × 100"),
 make("median-calculator","Median Calculator","Find the middle value in a list of numbers.","Everyday","Median is the middle sorted value or the mean of two middle values"),
 make("mode-calculator","Mode Calculator","Find the most frequently occurring values in a number list.","Everyday","Mode is the value or values with the highest frequency"),
 make("standard-deviation-calculator","Standard Deviation Calculator","Calculate population and sample standard deviation.","Everyday","Standard deviation is the square root of variance"),
 make("triangle-area-calculator","Triangle Area Calculator","Calculate triangle area from its base and height.","Everyday","Area = base × height ÷ 2"),
 make("circle-calculator","Circle Calculator","Calculate circle area, circumference, and diameter.","Everyday","Area = πr² and circumference = 2πr"),
 make("pythagorean-theorem-calculator","Pythagorean Theorem Calculator","Find the hypotenuse of a right triangle.","Everyday","c = √(a² + b²)"),
 make("running-pace-calculator","Running Pace Calculator","Calculate pace per mile or kilometer from distance and time.","Everyday","Pace = total time ÷ distance"),
 make("fuel-cost-calculator","Fuel Cost Calculator","Estimate trip fuel use and cost.","Everyday","Trip cost = distance ÷ fuel economy × fuel price"),
 make("fuel-economy-calculator","Fuel Economy Calculator","Calculate miles per gallon from distance and fuel used.","Everyday","Fuel economy = distance ÷ fuel used"),
 make("roi-calculator","ROI Calculator","Calculate investment gain and return on investment.","Finance","ROI = (ending value − initial value) ÷ initial value × 100"),
 make("apy-calculator","APY Calculator","Calculate annual percentage yield from a stated rate and compounding frequency.","Finance","APY = (1 + rate ÷ periods)ᵖᵉʳⁱᵒᵈˢ − 1"),
 make("inflation-calculator","Inflation Calculator","Estimate the future cost of money after inflation.","Finance","Future cost = current amount × (1 + inflation rate)ʸᵉᵃʳˢ"),
 make("salary-calculator","Annual Salary Calculator","Convert a regular paycheck into gross annual salary.","Finance","Annual salary = pay per period × periods per year"),
 make("hourly-to-salary-calculator","Hourly to Salary Calculator","Convert an hourly wage into weekly, monthly, and annual pay.","Finance","Annual pay = hourly rate × weekly hours × working weeks"),
 make("overtime-pay-calculator","Overtime Pay Calculator","Estimate regular and overtime gross pay.","Finance","Overtime pay = overtime hours × rate × overtime multiplier"),
 make("commission-calculator","Commission Calculator","Calculate commission earnings and total compensation.","Finance","Commission = eligible sales × commission rate"),
 make("emergency-fund-calculator","Emergency Fund Calculator","Estimate an emergency savings target from monthly expenses.","Finance","Target = essential monthly expenses × months of coverage"),
 make("retirement-withdrawal-calculator","Retirement Withdrawal Calculator","Estimate an annual and monthly portfolio withdrawal.","Finance","Annual withdrawal = portfolio balance × withdrawal rate"),
 make("board-foot-calculator","Board Foot Calculator","Calculate lumber volume in board feet.","Construction","Board feet = thickness × width × length ÷ 12"),
 make("mulch-calculator","Mulch Calculator","Estimate cubic yards of mulch for a landscaped area.","Construction","Cubic yards = length × width × depth ÷ 324"),
 make("tile-calculator","Tile Calculator","Estimate tiles needed for an area with waste.","Construction","Tiles = project area ÷ tile area × waste factor"),
 make("brick-calculator","Brick Calculator","Estimate bricks needed for a wall including waste.","Construction","Bricks = wall area × bricks per square foot × waste factor"),
 make("fence-calculator","Fence Calculator","Estimate fence panels and posts for a straight run.","Construction","Panels = fence length ÷ panel width, rounded up"),
 make("decking-calculator","Decking Calculator","Estimate deck boards from deck size and board coverage.","Construction","Boards = deck width ÷ effective board width"),
 make("asphalt-calculator","Asphalt Calculator","Estimate asphalt volume and weight for a paved area.","Construction","Weight = area × depth × asphalt density"),
 make("customer-acquisition-cost-calculator","Customer Acquisition Cost Calculator","Calculate average marketing and sales cost per new customer.","Business","CAC = acquisition spending ÷ new customers"),
 make("customer-lifetime-value-calculator","Customer Lifetime Value Calculator","Estimate gross customer value over a relationship.","Business","LTV = average purchase × purchase frequency × lifespan × margin"),
 make("churn-rate-calculator","Customer Churn Rate Calculator","Calculate the percentage of customers lost during a period.","Business","Churn = customers lost ÷ customers at start × 100"),
];

const calculatorBatchThree: ToolDefinition[] = [
 make("weighted-average-calculator","Weighted Average Calculator","Calculate an average where values have different weights.","Everyday","Weighted average = sum of value × weight ÷ sum of weights"),
 make("margin-of-error-calculator","Margin of Error Calculator","Estimate a survey margin of error for a proportion.","Everyday","Margin of error = z × √(p(1−p) ÷ sample size)"),
 make("z-score-calculator","Z-Score Calculator","Find how many standard deviations a value is from the mean.","Everyday","Z = (value − mean) ÷ standard deviation"),
 make("permutation-calculator","Permutation Calculator","Count ordered selections from a group.","Everyday","P(n,r) = n! ÷ (n−r)!"),
 make("combination-calculator","Combination Calculator","Count selections where order does not matter.","Everyday","C(n,r) = n! ÷ (r!(n−r)!)"),
 make("factorial-calculator","Factorial Calculator","Calculate the product of all positive integers up to a number.","Everyday","n! = n × (n−1) × … × 1"),
 make("exponent-calculator","Exponent Calculator","Raise a base number to a chosen power.","Everyday","Result = baseᵉˣᵖᵒⁿᵉⁿᵗ"),
 make("square-root-calculator","Square Root Calculator","Calculate the principal square root of a number.","Everyday","Square root × square root = original number"),
 make("net-worth-calculator","Net Worth Calculator","Compare total assets with total liabilities.","Finance","Net worth = total assets − total liabilities"),
 make("monthly-cash-flow-calculator","Monthly Cash Flow Calculator","Calculate money remaining after monthly expenses.","Finance","Cash flow = monthly income − monthly expenses"),
 make("loan-to-value-calculator","Loan-to-Value Calculator","Compare a loan balance with property value.","Finance","LTV = loan amount ÷ property value × 100"),
 make("down-payment-calculator","Down Payment Calculator","Calculate down payment amount and resulting loan balance.","Finance","Down payment = purchase price × down payment rate"),
 make("rent-affordability-calculator","Rent Affordability Calculator","Estimate a rent budget from gross monthly income.","Finance","Suggested rent = gross monthly income × selected housing rate"),
 make("savings-rate-calculator","Savings Rate Calculator","Measure savings as a percentage of take-home income.","Finance","Savings rate = monthly savings ÷ take-home income × 100"),
 make("dividend-yield-calculator","Dividend Yield Calculator","Calculate annual dividend income relative to share price.","Finance","Dividend yield = annual dividend per share ÷ share price × 100"),
 make("rule-of-72-calculator","Rule of 72 Calculator","Estimate how long money may take to double.","Finance","Doubling time ≈ 72 ÷ annual return rate"),
 make("room-volume-calculator","Room Volume Calculator","Calculate a room's cubic volume.","Construction","Volume = length × width × height"),
 make("wallpaper-calculator","Wallpaper Calculator","Estimate wallpaper rolls for a room.","Construction","Rolls = wall area ÷ usable coverage, rounded up"),
 make("topsoil-calculator","Topsoil Calculator","Estimate cubic yards of topsoil for a rectangular area.","Construction","Cubic yards = length × width × depth ÷ 324"),
 make("sand-calculator","Sand Calculator","Estimate sand volume and approximate weight.","Construction","Volume = length × width × depth"),
 make("siding-calculator","Siding Calculator","Estimate siding area after subtracting openings and adding waste.","Construction","Order area = (wall area − openings) × waste factor"),
 make("insulation-calculator","Insulation Calculator","Estimate insulation packages from coverage area.","Construction","Packages = area ÷ package coverage, rounded up"),
 make("wall-stud-calculator","Wall Stud Calculator","Estimate wall studs based on spacing and wall length.","Construction","Studs = wall length ÷ spacing + end stud"),
 make("average-order-value-calculator","Average Order Value Calculator","Calculate average revenue earned per order.","Business","AOV = total revenue ÷ number of orders"),
 make("cart-abandonment-rate-calculator","Cart Abandonment Rate Calculator","Calculate the share of shopping carts that did not convert.","Business","Abandonment = (created carts − purchases) ÷ created carts × 100"),
 make("gross-profit-calculator","Gross Profit Calculator","Calculate gross profit and gross margin from revenue and direct costs.","Business","Gross profit = revenue − cost of goods sold"),
];

const mathCalculatorBatch: ToolDefinition[] = [
 make("quadratic-formula-calculator","Quadratic Formula Calculator","Solve quadratic equations and identify real or complex roots.","Everyday","x = (−b ± √(b²−4ac)) ÷ 2a"),
 make("slope-calculator","Slope Calculator","Calculate the slope between two coordinate points.","Everyday","Slope = (y₂ − y₁) ÷ (x₂ − x₁)"),
 make("distance-between-points-calculator","Distance Between Two Points Calculator","Find the straight-line distance between two coordinates.","Everyday","Distance = √((x₂−x₁)² + (y₂−y₁)²)"),
 make("midpoint-calculator","Midpoint Calculator","Find the point halfway between two coordinates.","Everyday","Midpoint = ((x₁+x₂)÷2, (y₁+y₂)÷2)"),
 make("linear-equation-calculator","Linear Equation Calculator","Calculate y from slope, x, and y-intercept.","Everyday","y = mx + b"),
 make("absolute-value-calculator","Absolute Value Calculator","Find a number's distance from zero.","Everyday","|x| is x when x ≥ 0 and −x when x < 0"),
 make("logarithm-calculator","Logarithm Calculator","Calculate a logarithm using a chosen base.","Everyday","log base b of x = ln(x) ÷ ln(b)"),
 make("natural-log-calculator","Natural Log Calculator","Calculate the natural logarithm of a positive number.","Everyday","Natural logarithm uses base e"),
 make("cube-root-calculator","Cube Root Calculator","Calculate the real cube root of a number.","Everyday","Cube root of x = x raised to ⅓"),
 make("nth-root-calculator","Nth Root Calculator","Calculate any positive integer root of a number.","Everyday","Nth root of x = x raised to 1÷n"),
 make("geometric-mean-calculator","Geometric Mean Calculator","Find the multiplicative average of positive values.","Everyday","Geometric mean = nth root of the values' product"),
 make("harmonic-mean-calculator","Harmonic Mean Calculator","Find the harmonic mean of a number list.","Everyday","Harmonic mean = n ÷ sum of reciprocals"),
 make("variance-calculator","Variance Calculator","Calculate population and sample variance.","Everyday","Variance is the average squared distance from the mean"),
 make("range-calculator","Range Calculator","Find the difference between the largest and smallest values.","Everyday","Range = maximum − minimum"),
 make("sum-calculator","Sum Calculator","Add a list of numbers and count its values.","Everyday","Sum = value₁ + value₂ + …"),
 make("prime-number-calculator","Prime Number Calculator","Check whether a whole number is prime.","Everyday","A prime number has exactly two positive divisors"),
 make("prime-factorization-calculator","Prime Factorization Calculator","Break a whole number into prime factors.","Everyday","Prime factors multiply to the original number"),
 make("least-common-multiple-calculator","Least Common Multiple Calculator","Find the smallest positive multiple shared by two numbers.","Everyday","LCM(a,b) = |a×b| ÷ GCF(a,b)"),
 make("greatest-common-factor-calculator","Greatest Common Factor Calculator","Find the largest factor shared by two integers.","Everyday","GCF uses the Euclidean algorithm"),
 make("modulo-calculator","Modulo Calculator","Find the remainder after dividing two integers.","Everyday","a mod b = remainder after a ÷ b"),
 make("fraction-simplifier","Fraction Simplifier","Reduce a fraction to its lowest terms.","Everyday","Divide numerator and denominator by their GCF"),
 make("decimal-to-fraction-calculator","Decimal to Fraction Calculator","Convert a decimal into a simplified fraction.","Everyday","Decimal places determine the initial denominator"),
 make("adding-fractions-calculator","Adding Fractions Calculator","Add two fractions and simplify the result.","Everyday","a÷b + c÷d = (ad + bc) ÷ bd"),
 make("multiplying-fractions-calculator","Multiplying Fractions Calculator","Multiply two fractions and simplify the result.","Everyday","a÷b × c÷d = ac ÷ bd"),
 make("arithmetic-sequence-calculator","Arithmetic Sequence Calculator","Find the nth term and sum of an arithmetic sequence.","Everyday","aₙ = a₁ + (n−1)d"),
];

const calculatorBatchFive: ToolDefinition[] = [
 make("rectangle-calculator","Rectangle Calculator","Calculate rectangle area, perimeter, and diagonal.","Math","Area = length × width"),
 make("trapezoid-area-calculator","Trapezoid Area Calculator","Calculate area from two parallel bases and height.","Math","Area = (base₁ + base₂) × height ÷ 2"),
 make("parallelogram-area-calculator","Parallelogram Area Calculator","Calculate parallelogram area and perimeter.","Math","Area = base × perpendicular height"),
 make("sphere-calculator","Sphere Calculator","Calculate sphere volume and surface area from radius.","Math","Volume = 4÷3 × πr³"),
 make("cylinder-calculator","Cylinder Calculator","Calculate cylinder volume and surface area.","Math","Volume = πr²h"),
 make("cone-calculator","Cone Calculator","Calculate cone volume, slant height, and surface area.","Math","Volume = πr²h ÷ 3"),
 make("rectangular-prism-calculator","Rectangular Prism Calculator","Calculate box volume and surface area.","Math","Volume = length × width × height"),
 make("polygon-interior-angle-calculator","Polygon Interior Angle Calculator","Calculate interior-angle totals and regular polygon angles.","Math","Interior angle sum = (sides − 2) × 180°"),
 make("recipe-scaling-calculator","Recipe Scaling Calculator","Scale an ingredient amount for a different number of servings.","Everyday","New amount = original amount × desired servings ÷ original servings"),
 make("unit-price-calculator","Unit Price Calculator","Compare product cost based on quantity.","Everyday","Unit price = total price ÷ quantity"),
 make("price-per-square-foot-calculator","Price Per Square Foot Calculator","Calculate property or project cost per square foot.","Everyday","Price per square foot = total price ÷ total area"),
 make("split-bill-calculator","Split Bill Calculator","Split a bill, tax, and tip across a group.","Everyday","Per-person share = total bill ÷ number of people"),
 make("cagr-calculator","CAGR Calculator","Calculate compound annual growth rate between two values.","Finance","CAGR = (ending value ÷ beginning value)^(1÷years) − 1"),
 make("future-value-calculator","Future Value Calculator","Estimate the future value of a lump sum.","Finance","Future value = present value × (1 + rate)ʸᵉᵃʳˢ"),
 make("present-value-calculator","Present Value Calculator","Discount a future amount into today's value.","Finance","Present value = future value ÷ (1 + rate)ʸᵉᵃʳˢ"),
 make("effective-annual-rate-calculator","Effective Annual Rate Calculator","Convert a nominal rate into an effective annual rate.","Finance","EAR = (1 + nominal rate ÷ periods)ᵖᵉʳⁱᵒᵈˢ − 1"),
 make("investment-fee-calculator","Investment Fee Calculator","Estimate how annual fees can affect investment growth.","Finance","Fee-adjusted growth uses return rate minus annual fee"),
 make("debt-payment-ratio-calculator","Debt Payment Ratio Calculator","Measure debt payments against take-home income.","Finance","Debt payment ratio = monthly debt payments ÷ take-home income × 100"),
 make("revenue-growth-calculator","Revenue Growth Calculator","Calculate revenue growth between two periods.","Business","Growth = (new revenue − old revenue) ÷ old revenue × 100"),
 make("inventory-turnover-calculator","Inventory Turnover Calculator","Measure how often inventory is sold during a period.","Business","Turnover = cost of goods sold ÷ average inventory"),
 make("freelance-rate-calculator","Freelance Hourly Rate Calculator","Estimate a sustainable hourly rate from income and expense goals.","Business","Hourly rate = (income goal + expenses) ÷ billable hours"),
 make("excavation-calculator","Excavation Calculator","Estimate soil volume removed from a rectangular excavation.","Construction","Volume = length × width × depth"),
 make("paver-calculator","Paver Calculator","Estimate paving units required for a surface with waste.","Construction","Pavers = project area ÷ paver area × waste factor"),
 make("pool-volume-calculator","Pool Volume Calculator","Estimate rectangular pool volume in gallons.","Construction","Gallons = length × width × average depth × 7.48052"),
 make("stair-calculator","Stair Calculator","Estimate stair riser count and actual riser height.","Construction","Risers = total rise ÷ target riser height, rounded"),
];

const measurementBatch: ToolDefinition[] = [
 make("pressure-converter","Pressure Converter","Convert pascals, kilopascals, bar, PSI, and atmospheres.","Converters","Converted pressure = input × source factor ÷ target factor"),
 make("energy-converter","Energy Converter","Convert joules, kilojoules, calories, watt-hours, and BTU.","Converters","Converted energy = input × source factor ÷ target factor"),
 make("power-converter","Power Converter","Convert watts, kilowatts, horsepower, and BTU per hour.","Converters","Converted power = input × source factor ÷ target factor"),
 make("angle-converter","Angle Converter","Convert degrees, radians, gradians, and turns.","Converters","Converted angle = input × source factor ÷ target factor"),
 make("force-converter","Force Converter","Convert newtons, kilonewtons, pound-force, and kilogram-force.","Converters","Converted force = input × source factor ÷ target factor"),
 make("torque-converter","Torque Converter","Convert newton-meters, pound-feet, and pound-inches.","Converters","Converted torque = input × source factor ÷ target factor"),
 make("density-converter","Density Converter","Convert density between metric and imperial units.","Converters","Converted density = input × source factor ÷ target factor"),
 make("time-converter","Time Converter","Convert seconds, minutes, hours, days, and weeks.","Converters","Converted time = input × source factor ÷ target factor"),
 make("frequency-converter","Frequency Converter","Convert hertz, kilohertz, megahertz, and gigahertz.","Converters","Converted frequency = input × source factor ÷ target factor"),
 make("acceleration-converter","Acceleration Converter","Convert meters per second squared, feet per second squared, and g-force.","Converters","Converted acceleration = input × source factor ÷ target factor"),
 make("flow-rate-converter","Flow Rate Converter","Convert liters per minute, gallons per minute, and cubic meters per hour.","Converters","Converted flow = input × source factor ÷ target factor"),
 make("cooking-measurement-converter","Cooking Measurement Converter","Convert teaspoons, tablespoons, cups, milliliters, and liters.","Converters","Converted volume = input × source factor ÷ target factor"),
 make("typography-unit-converter","Typography Unit Converter","Convert pixels, points, picas, and rem units.","Developer","CSS conversion uses a selected 16-pixel root size"),
 make("fuel-economy-converter","Fuel Economy Converter","Convert MPG, kilometers per liter, and liters per 100 kilometers.","Converters","Fuel economy conversion accounts for reciprocal consumption units"),
 make("data-rate-converter","Data Rate Converter","Convert bits and bytes per second from kilobits through gigabytes.","Developer","Eight bits equal one byte"),
];

const utilityBatch: ToolDefinition[] = [
 make("slug-generator","SEO Slug Generator","Turn a title or phrase into a clean URL slug.","Business","A slug uses lowercase words separated by hyphens"),
 make("case-converter","Text Case Converter","Convert text to uppercase, lowercase, title case, or sentence case.","Developer","Case conversion changes letter capitalization without changing words"),
 make("keyword-density-checker","Keyword Density Checker","Measure how often a keyword appears in text.","Business","Density = keyword occurrences ÷ total words × 100"),
 make("meta-title-checker","Meta Title Length Checker","Check title length against practical search-result guidelines.","Business","Counts visible characters in a proposed SEO title"),
 make("meta-description-checker","Meta Description Length Checker","Check the length of a proposed search description.","Business","Counts visible characters in a proposed meta description"),
 make("word-frequency-counter","Word Frequency Counter","Find the most common words in pasted text.","Developer","Words are normalized and counted by frequency"),
 make("url-parser","URL Parser","Break a URL into protocol, host, path, query, and fragment.","Developer","A URL is separated into standard address components"),
 make("query-string-parser","Query String Parser","Turn URL query parameters into readable key-value pairs.","Developer","Query parameters follow the question mark in a URL"),
 make("json-to-csv-converter","JSON to CSV Converter","Convert an array of JSON objects into CSV.","Developer","Object keys become CSV column headers"),
 make("csv-to-json-converter","CSV to JSON Converter","Convert comma-separated rows into JSON objects.","Developer","The first CSV row supplies object keys"),
 make("html-entity-encoder","HTML Entity Encoder and Decoder","Encode reserved HTML characters or decode entities.","Developer","Reserved characters can be represented as HTML entities"),
 make("number-base-converter","Number Base Converter","Convert integers between binary, octal, decimal, and hexadecimal.","Developer","Base conversion preserves the underlying integer value"),
 make("hex-rgb-converter","HEX and RGB Color Converter","Convert hexadecimal colors into RGB values and back.","Developer","HEX pairs represent red, green, and blue channels"),
 make("uuid-generator","UUID Generator","Generate random version 4 UUID identifiers locally.","Developer","A UUID v4 contains random hexadecimal groups"),
 make("password-generator","Password Generator","Generate a strong random password in your browser.","Developer","Random characters are selected from multiple character sets"),
 make("sort-lines-tool","Sort Lines Tool","Sort lines alphabetically in ascending or descending order.","Developer","Each nonempty line is treated as one sortable item"),
 make("remove-duplicate-lines","Duplicate Line Remover","Remove repeated lines while preserving their first occurrence.","Developer","Each line is compared with earlier lines"),
 make("whitespace-cleaner","Whitespace Cleaner","Remove extra spaces and blank lines from text.","Developer","Repeated whitespace is reduced while paragraph breaks remain"),
 make("reverse-text-tool","Reverse Text Tool","Reverse characters or line order instantly.","Developer","Character order or line order is reversed locally"),
 make("regex-tester","Regular Expression Tester","Test a JavaScript regular expression against text.","Developer","Matches use JavaScript regular-expression syntax"),
 make("lorem-ipsum-generator","Lorem Ipsum Generator","Generate placeholder paragraphs for layouts and prototypes.","Developer","Produces a selected amount of neutral placeholder copy"),
 make("css-minifier","CSS Minifier","Remove comments and unnecessary whitespace from CSS.","Developer","Minification reduces formatting without changing valid CSS rules"),
 make("javascript-string-escaper","JavaScript String Escaper","Escape or unescape text for use inside JavaScript strings.","Developer","Quotes, slashes, and control characters receive escape sequences"),
 make("email-list-cleaner","Email List Cleaner","Normalize, deduplicate, and sort email addresses.","Business","Addresses are trimmed, lowercased, and deduplicated"),
 make("number-list-cleaner","Number List Cleaner","Extract, sort, and deduplicate numbers from mixed text.","Developer","Numeric values are detected and normalized"),
];

const marketingCalculatorBatch: ToolDefinition[] = [
 make("acos-calculator","ACoS Calculator","Calculate advertising cost of sales from ad spend and attributed sales.","Business","ACoS = ad spend ÷ attributed sales × 100"),
 make("tacos-calculator","TACoS Calculator","Measure advertising spend against total sales.","Business","TACoS = ad spend ÷ total sales × 100"),
 make("marketing-efficiency-ratio-calculator","Marketing Efficiency Ratio Calculator","Calculate total revenue returned for each marketing dollar.","Business","MER = total revenue ÷ total marketing spend"),
 make("break-even-acos-calculator","Break-Even ACoS Calculator","Estimate the highest ACoS before product profit reaches zero.","Business","Break-even ACoS = pre-ad profit ÷ selling price × 100"),
 make("ppc-profit-calculator","PPC Profit Calculator","Estimate profit after product costs and advertising spend.","Business","Profit = ad sales − product costs − ad spend"),
 make("contribution-margin-calculator","Contribution Margin Calculator","Calculate contribution profit and margin per unit.","Business","Contribution margin = selling price − variable cost"),
 make("target-cpa-calculator","Target CPA Calculator","Estimate an affordable acquisition cost from order value and margin.","Business","Target CPA = order value × contribution margin rate"),
 make("cost-per-lead-calculator","Cost Per Lead Calculator","Calculate average campaign spend for each lead.","Business","CPL = campaign spend ÷ leads"),
 make("lead-to-customer-rate-calculator","Lead-to-Customer Rate Calculator","Measure the percentage of leads that become customers.","Business","Close rate = new customers ÷ leads × 100"),
 make("email-open-rate-calculator","Email Open Rate Calculator","Calculate unique email opens as a percentage of delivered messages.","Business","Open rate = unique opens ÷ delivered emails × 100"),
 make("email-click-rate-calculator","Email Click Rate Calculator","Calculate unique email clicks against delivered messages.","Business","Click rate = unique clicks ÷ delivered emails × 100"),
 make("email-unsubscribe-rate-calculator","Email Unsubscribe Rate Calculator","Calculate unsubscribes as a percentage of delivered messages.","Business","Unsubscribe rate = unsubscribes ÷ delivered emails × 100"),
 make("website-bounce-rate-calculator","Website Bounce Rate Calculator","Calculate single-page sessions as a percentage of sessions.","Business","Bounce rate = bounced sessions ÷ total sessions × 100"),
 make("social-engagement-rate-calculator","Social Engagement Rate Calculator","Measure social interactions against reach or followers.","Business","Engagement rate = interactions ÷ audience × 100"),
 make("follower-growth-rate-calculator","Follower Growth Rate Calculator","Measure net follower growth during a period.","Business","Growth rate = net new followers ÷ starting followers × 100"),
 make("revenue-per-visitor-calculator","Revenue Per Visitor Calculator","Calculate average revenue earned for each website visitor.","Business","RPV = website revenue ÷ visitors"),
 make("revenue-per-employee-calculator","Revenue Per Employee Calculator","Calculate company revenue divided by employee count.","Business","Revenue per employee = annual revenue ÷ employees"),
 make("repeat-purchase-rate-calculator","Repeat Purchase Rate Calculator","Measure customers who bought more than once.","Business","Repeat purchase rate = repeat customers ÷ total customers × 100"),
 make("refund-rate-calculator","Refund Rate Calculator","Calculate refunded orders as a percentage of orders.","Business","Refund rate = refunded orders ÷ total orders × 100"),
 make("product-return-rate-calculator","Product Return Rate Calculator","Calculate returned units as a percentage of units sold.","Business","Return rate = returned units ÷ units sold × 100"),
 make("days-in-inventory-calculator","Days in Inventory Calculator","Estimate the average days inventory remains before sale.","Business","Days in inventory = average inventory ÷ COGS × days"),
 make("sell-through-rate-calculator","Sell-Through Rate Calculator","Measure units sold against available inventory.","Business","Sell-through = units sold ÷ units available × 100"),
 make("ad-frequency-calculator","Advertising Frequency Calculator","Calculate average ad exposures per reached person.","Business","Frequency = impressions ÷ reach"),
 make("impression-share-calculator","Impression Share Calculator","Estimate eligible impressions captured by a campaign.","Business","Impression share = received impressions ÷ eligible impressions × 100"),
 make("campaign-budget-pacing-calculator","Campaign Budget Pacing Calculator","Compare expected spend with actual spend during a campaign.","Business","Expected spend = total budget × elapsed days ÷ campaign days"),
];

const mathCalculatorBatchTwo: ToolDefinition[] = [
 make("basic-calculator","Basic Calculator","Add, subtract, multiply, or divide two numbers with a simple calculator.","Math","Result = first number selected operation second number"),
 make("subtracting-fractions-calculator","Subtracting Fractions Calculator","Subtract two fractions and simplify the result.","Math","a÷b − c÷d = (ad − bc) ÷ bd"),
 make("dividing-fractions-calculator","Dividing Fractions Calculator","Divide two fractions and simplify the result.","Math","a÷b ÷ c÷d = ad ÷ bc"),
 make("proportion-calculator","Proportion Calculator","Solve a missing value in two equal ratios.","Math","a ÷ b = c ÷ x"),
 make("mixed-number-calculator","Mixed Number Calculator","Convert an improper fraction into a mixed number.","Math","Mixed number = whole quotient plus remainder over denominator"),
 make("scientific-notation-calculator","Scientific Notation Calculator","Write a number in normalized scientific notation.","Math","Number = coefficient × 10ᵉˣᵖᵒⁿᵉⁿᵗ"),
 make("rounding-calculator","Rounding Calculator","Round a number to a selected number of decimal places.","Math","Rounded value uses the next digit to determine direction"),
 make("significant-figures-calculator","Significant Figures Calculator","Round a number to a selected count of significant figures.","Math","Significant figures begin at the first nonzero digit"),
 make("quadratic-discriminant-calculator","Quadratic Discriminant Calculator","Calculate a quadratic discriminant and identify the root type.","Math","Discriminant = b² − 4ac"),
 make("two-variable-equation-calculator","Two-Variable Equation Calculator","Solve a pair of linear equations in x and y.","Math","Cramer's rule solves a₁x + b₁y = c₁ and a₂x + b₂y = c₂"),
 make("matrix-determinant-calculator","2×2 Matrix Determinant Calculator","Calculate the determinant of a two-by-two matrix.","Math","Determinant = ad − bc"),
 make("right-triangle-calculator","Right Triangle Calculator","Calculate the hypotenuse, area, and perimeter from two legs.","Math","Hypotenuse = √(a² + b²)"),
 make("triangle-perimeter-calculator","Triangle Perimeter Calculator","Add three side lengths and check whether they form a triangle.","Math","Perimeter = side a + side b + side c"),
 make("ellipse-area-calculator","Ellipse Area Calculator","Calculate ellipse area from its two semi-axis lengths.","Math","Area = πab"),
 make("sector-area-calculator","Sector Area Calculator","Calculate the area of a circular sector.","Math","Sector area = angle ÷ 360 × πr²"),
 make("arc-length-calculator","Arc Length Calculator","Calculate circular arc length from radius and central angle.","Math","Arc length = angle ÷ 360 × 2πr"),
 make("regular-polygon-area-calculator","Regular Polygon Area Calculator","Calculate a regular polygon's area and perimeter.","Math","Area = n × s² ÷ (4 tan(π÷n))"),
 make("geometric-sequence-calculator","Geometric Sequence Calculator","Find the nth term and finite sum of a geometric sequence.","Math","aₙ = a₁ × rⁿ⁻¹"),
 make("mean-absolute-deviation-calculator","Mean Absolute Deviation Calculator","Measure the average distance of values from their mean.","Math","MAD = sum of absolute deviations ÷ number of values"),
 make("probability-calculator","Probability Calculator","Calculate event probability and its complement from outcomes.","Math","Probability = favorable outcomes ÷ total outcomes"),
 make("odds-probability-converter","Odds and Probability Converter","Convert odds in favor into probability and percentage.","Math","Probability = favorable odds ÷ total odds"),
];

const finalMathCalculatorBatch: ToolDefinition[] = [
 make("cube-calculator","Cube Calculator","Calculate a cube's volume, surface area, and space diagonal.","Math","Volume = side³"),
 make("square-calculator","Square Calculator","Calculate a square's area, perimeter, and diagonal.","Math","Area = side²"),
 make("percent-error-calculator","Percent Error Calculator","Compare an observed value with an accepted value.","Math","Percent error = |observed − accepted| ÷ |accepted| × 100"),
 make("herons-formula-calculator","Heron's Formula Calculator","Calculate triangle area from three side lengths.","Math","Area = √(s(s−a)(s−b)(s−c))"),
 make("law-of-cosines-calculator","Law of Cosines Calculator","Find the third side from two sides and their included angle.","Math","c² = a² + b² − 2ab cos(C)"),
 make("law-of-sines-calculator","Law of Sines Calculator","Find a missing side from a known side and two angles.","Math","a ÷ sin(A) = b ÷ sin(B)"),
 make("three-dimensional-distance-calculator","3D Distance Calculator","Find the distance between two points in three-dimensional space.","Math","Distance = √((x₂−x₁)² + (y₂−y₁)² + (z₂−z₁)²)"),
 make("annulus-area-calculator","Annulus Area Calculator","Calculate the area between two concentric circles.","Math","Area = π(R² − r²)"),
 make("sector-perimeter-calculator","Sector Perimeter Calculator","Calculate a circular sector's arc length and perimeter.","Math","Perimeter = 2r + angle ÷ 360 × 2πr"),
 make("expected-value-calculator","Expected Value Calculator","Calculate the expected value of two possible outcomes.","Math","Expected value = outcome₁ × probability₁ + outcome₂ × probability₂"),
 make("coefficient-of-variation-calculator","Coefficient of Variation Calculator","Compare standard deviation with the mean as a percentage.","Math","CV = standard deviation ÷ mean × 100"),
 make("standard-error-calculator","Standard Error Calculator","Estimate the standard error of a sample mean.","Math","Standard error = standard deviation ÷ √sample size"),
 make("sample-size-calculator","Sample Size Calculator","Estimate survey sample size for a proportion and margin of error.","Math","Sample size = z²p(1−p) ÷ e²"),
 make("midrange-calculator","Midrange Calculator","Find the value halfway between a minimum and maximum.","Math","Midrange = (minimum + maximum) ÷ 2"),
];

const threeHundredToolBatch: ToolDefinition[] = [
 make("aspect-ratio-calculator","Aspect Ratio Calculator","Calculate and simplify screen or image aspect ratios.","Developer","Aspect ratio = width ÷ height"),
 make("screen-resolution-scaler","Screen Resolution Scaler","Scale image or screen dimensions while preserving proportion.","Developer","New height = original height × new width ÷ original width"),
 make("px-to-rem-calculator","PX to REM Calculator","Convert pixels and rem units using a chosen root size.","Developer","rem = pixels ÷ root font size"),
 make("css-clamp-calculator","CSS Clamp Calculator","Calculate a fluid preferred size between minimum and maximum values.","Developer","Preferred size = base size + viewport factor"),
 make("download-time-calculator","Download Time Calculator","Estimate download time from file size and connection speed.","Developer","Time = file size in bits ÷ speed in bits per second"),
 make("api-rate-limit-calculator","API Rate Limit Calculator","Calculate request capacity across a selected time period.","Developer","Capacity = requests per interval × total intervals"),
 make("database-storage-calculator","Database Storage Calculator","Estimate database size from records and bytes per record.","Developer","Storage = records × average bytes per record"),
 make("image-file-size-calculator","Image File Size Calculator","Estimate uncompressed image size from dimensions and color depth.","Developer","Size = width × height × bits per pixel ÷ 8"),
 make("video-file-size-calculator","Video File Size Calculator","Estimate video file size from bitrate and duration.","Developer","File size = bitrate × duration ÷ 8"),
 make("audio-file-size-calculator","Audio File Size Calculator","Estimate uncompressed audio size from sample rate, depth, channels, and duration.","Developer","Size = sample rate × bit depth × channels × duration ÷ 8"),
 make("grid-column-width-calculator","CSS Grid Column Width Calculator","Calculate column width from container size, gaps, and column count.","Developer","Column width = (container − total gaps) ÷ columns"),
 make("cache-hit-rate-calculator","Cache Hit Rate Calculator","Measure successful cache requests and miss rate.","Developer","Hit rate = cache hits ÷ total requests × 100"),
 make("server-capacity-calculator","Server Capacity Calculator","Estimate concurrent request capacity from throughput and response time.","Developer","Concurrency = requests per second × response time"),
 make("uptime-calculator","Website Uptime Calculator","Convert downtime into an uptime percentage.","Developer","Uptime = available time ÷ total time × 100"),
 make("availability-downtime-calculator","Availability Downtime Calculator","Estimate permitted downtime from an availability target.","Developer","Downtime = period length × (1 − availability)"),
 make("data-transfer-cost-calculator","Data Transfer Cost Calculator","Estimate bandwidth cost from transfer volume and unit price.","Developer","Cost = transferred gigabytes × price per gigabyte"),
 make("concurrent-users-calculator","Concurrent Users Calculator","Estimate concurrent users from traffic, visit duration, and time period.","Developer","Concurrency = visits × average duration ÷ period duration"),
 make("requests-per-second-calculator","Requests Per Second Calculator","Convert total requests over time into average throughput.","Developer","RPS = total requests ÷ elapsed seconds"),
 make("compression-ratio-calculator","Compression Ratio Calculator","Measure file-size reduction after compression.","Developer","Compression ratio = original size ÷ compressed size"),
 make("responsive-breakpoint-calculator","Responsive Breakpoint Calculator","Divide a viewport range into evenly spaced breakpoint intervals.","Developer","Step = (maximum width − minimum width) ÷ intervals"),
 make("sum-of-squares-calculator","Sum of Squares Calculator","Calculate the sum of five squared values.","Math","Sum of squares = x₁² + x₂² + …"),
 make("difference-of-squares-calculator","Difference of Squares Calculator","Calculate and factor the difference between two squares.","Math","a² − b² = (a−b)(a+b)"),
 make("reciprocal-calculator","Reciprocal Calculator","Find the multiplicative inverse of a number.","Math","Reciprocal = 1 ÷ number"),
 make("power-of-ten-calculator","Power of Ten Calculator","Calculate ten raised to any exponent.","Math","Result = 10ᵉˣᵖᵒⁿᵉⁿᵗ"),
 make("degrees-to-radians-calculator","Degrees to Radians Calculator","Convert an angle from degrees to radians.","Math","Radians = degrees × π ÷ 180"),
 make("radians-to-degrees-calculator","Radians to Degrees Calculator","Convert an angle from radians to degrees.","Math","Degrees = radians × 180 ÷ π"),
 make("sine-calculator","Sine Calculator","Calculate the sine of an angle in degrees.","Math","Sine = sin(angle × π ÷ 180)"),
 make("cosine-calculator","Cosine Calculator","Calculate the cosine of an angle in degrees.","Math","Cosine = cos(angle × π ÷ 180)"),
 make("tangent-calculator","Tangent Calculator","Calculate the tangent of an angle in degrees.","Math","Tangent = tan(angle × π ÷ 180)"),
 make("inverse-sine-calculator","Inverse Sine Calculator","Calculate an angle from a sine value.","Math","Angle = arcsin(value)"),
 make("inverse-cosine-calculator","Inverse Cosine Calculator","Calculate an angle from a cosine value.","Math","Angle = arccos(value)"),
 make("inverse-tangent-calculator","Inverse Tangent Calculator","Calculate an angle from a tangent value.","Math","Angle = arctan(value)"),
 make("pentagon-area-calculator","Pentagon Area Calculator","Calculate the area and perimeter of a regular pentagon.","Math","Area = ¼√(5(5+2√5)) × side²"),
 make("hexagon-area-calculator","Hexagon Area Calculator","Calculate the area and perimeter of a regular hexagon.","Math","Area = 3√3 ÷ 2 × side²"),
 make("octagon-area-calculator","Octagon Area Calculator","Calculate the area and perimeter of a regular octagon.","Math","Area = 2(1+√2) × side²"),
 make("rhombus-area-calculator","Rhombus Area Calculator","Calculate rhombus area from its diagonals.","Math","Area = diagonal one × diagonal two ÷ 2"),
 make("kite-area-calculator","Kite Area Calculator","Calculate kite area from its perpendicular diagonals.","Math","Area = diagonal one × diagonal two ÷ 2"),
 make("semicircle-calculator","Semicircle Calculator","Calculate semicircle area and perimeter.","Math","Area = πr² ÷ 2"),
 make("hemisphere-calculator","Hemisphere Calculator","Calculate hemisphere volume and surface areas.","Math","Volume = 2πr³ ÷ 3"),
 make("pyramid-volume-calculator","Pyramid Volume Calculator","Calculate rectangular pyramid volume.","Math","Volume = length × width × height ÷ 3"),
 make("triangular-prism-calculator","Triangular Prism Calculator","Calculate triangular prism volume.","Math","Volume = triangle base × triangle height ÷ 2 × prism length"),
 make("population-density-calculator","Population Density Calculator","Calculate people per unit of area.","Math","Density = population ÷ area"),
 make("relative-change-calculator","Relative Change Calculator","Measure change relative to an original value.","Math","Relative change = (new − original) ÷ |original| × 100"),
 make("weighted-percentage-calculator","Weighted Percentage Calculator","Combine three scores using percentage weights.","Math","Weighted result = sum of score × weight ÷ total weight"),
 make("pooled-mean-calculator","Pooled Mean Calculator","Combine two group means using their sample sizes.","Math","Pooled mean = (n₁m₁ + n₂m₂) ÷ (n₁+n₂)"),
 make("variance-from-standard-deviation-calculator","Variance From Standard Deviation Calculator","Convert standard deviation into variance.","Math","Variance = standard deviation²"),
 make("standard-deviation-from-variance-calculator","Standard Deviation From Variance Calculator","Convert variance into standard deviation.","Math","Standard deviation = √variance"),
 make("z-score-to-value-calculator","Z-Score to Value Calculator","Convert a z-score into a raw value.","Math","Value = mean + z-score × standard deviation"),
 make("relative-frequency-calculator","Relative Frequency Calculator","Calculate event frequency as a share of observations.","Math","Relative frequency = event count ÷ total count"),
 make("population-growth-calculator","Population Growth Calculator","Project compound population growth over time.","Math","Future population = current population × (1 + rate)ʸᵉᵃʳˢ"),
];

export const toolDefinitions: ToolDefinition[] = [...coreTools,...expandedTools,...calculatorBatchTwo,...calculatorBatchThree,...mathCalculatorBatch.map(tool=>({...tool,category:"Math"})),...calculatorBatchFive,...measurementBatch,...utilityBatch,...marketingCalculatorBatch,...mathCalculatorBatchTwo,...finalMathCalculatorBatch,...threeHundredToolBatch];
export const toolBySlug = Object.fromEntries(toolDefinitions.map((tool) => [tool.slug, tool]));
